### ISSUE TITLE
Add support for heat advisory icon

### ISSUE THREAD

**Issue by fencing49** [MrBartusek/MeteoalarmCard#102]
![Screenshot_20220720-054122_Home Assistant](https://user-images.githubusercontent.com/12490327/179951631-f34776e6-51e8-4e8f-959f-2b4031ac66e1.jpg)

As you could probably imagine most of the world right now is experiencing a pretty big heat advisory and I noticed the other day that there isn't an icon for this particular warning. It would be great if we had a separate icon for this.

**Comment by MrBartusek** [comment]
This issue lacks a lot of detail. Please [open a new issue with proper issue template](https://github.com/MrBartusek/MeteoalarmCard/issues/new?assignees=&labels=bug&template=bug_repport.yaml)
