### ISSUE TITLE
Is it possible to reduce the height in the frontend card on lovelace?

### ISSUE THREAD

**Issue by pcwankenobi** [MrBartusek/MeteoalarmCard#108]
Is it possible to reduce the height in the frontend card on lovelace?

**Comment by MrBartusek** [comment]
No there is currently no such ability. Why would you want to reduce the height?

**Comment by pcwankenobi** [comment]
Hi , ok no problem. The warning appears a bit big on Tablets.  Thats why I was wondering. Still awesome card tho.
