### ISSUE TITLE
Get card to show other text attribute from entity

### ISSUE THREAD

**Issue by bregtvandenbergh** [MrBartusek/MeteoalarmCard#110]
Dear, is there a way to show another attribute from the meteoalarm entity on the card? I use the dutch language. I would like the card to show attribute 'event' instead of attribute 'awareness type'.

Data from meteoalarm entity:

![IMG_20220811_111243](https://user-images.githubusercontent.com/31744864/184101531-7c72182c-88ab-4588-b22b-b2fb1b5e29b7.jpg)

Data appearing on card:

![IMG_20220811_111307](https://user-images.githubusercontent.com/31744864/184101618-104d2615-2138-4a4b-ab36-ec4e61e810a6.jpg)

Thanks

**Comment by MrBartusek** [comment]
Hey, this text is just too long to be displayed on card and the one you are seeing is a fallback.
