### ISSUE TITLE
Filter for alert severity

### ISSUE THREAD

**Issue by kalhimeo** [MrBartusek/MeteoalarmCard#112]
**Is your feature request related to a problem? Please describe.**
I use you card on a wall tablet, hiding it when there are no alerts. In my opinion, Yellow alerts (ie. for high temperatures) are not that important and I would rather not consume screen place for that, but I am very interested in seing any Red alert (ie.  storms).

**Describe the solution you'd like**
It would be great to have a filter in the card to only show alerts above a defined awareness_level, or even be able to filter out some awareness_type. Note that I am using MeteoAlarm integration as source and I don't know if the others are using the same entity attributes.

Thanks for the consideration and for the excellent card.

**Comment by MrBartusek** [comment]
That's a nice request. A couple of integrations actually allow for filtering alerts but most of them don't. I guess another thing that could be filtered here are alert types. That would need some internal changes so integrations actually provide all alert types that they can return, by manifest most likely.

**Comment by kalhimeo** [comment]
thanks for considering my request. I am not sure that the manifest from integrations is 100% required, it would be better of course, but to make it easier we could initially manually figure out which "names/values" we would like to filter out by checking the "name/value" which is actually showing and that we don t want to see anymore.

**Comment by MrBartusek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Meteoalarm Filters](https://trello.com/c/ZVnvmLKf/4-meteoalarm-filters)

**Comment by programmdesign** [comment]
Hi. I just was looking for the same thing. I'm not interested really in "level one" warnings from DWD. It'd be great if one could set the alert level from which on the banner is displayed.

**Comment by MrBartusek** [comment]
Hey! Thank you for your request, this feature will be part of the next release. You can configure your card to exclude events and levels like so:

```YAML
type: custom:meteoalarm-card
integration: env_canada
entities:
  - entity: sensor.sundre_warnings
ignored_levels:
  - Yellow
ignored_events:
  - Air Quality
```

Please refer to [README](https://github.com/MrBartusek/MeteoalarmCard#using-the-card) for more information
