### ISSUE TITLE
Issue with translation (and I haven't changed anything yet)

### ISSUE THREAD

**Issue by SiriosDev** [MrBartusek/MeteoalarmCard#114]
I don't know how to develop JS, but I could improve Italian translation, when I launch `npm start` I get the following error.

`Error loading "tslib" helper library.
[!] Error: Package subpath './package.json' is not defined by "exports" in C:\Users\ciaoa\Desktop\MeteoalarmCard\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json ..etcetc....`

what do I do?

**Comment by MrBartusek** [comment]
Node version?

**Comment by SiriosDev** [comment]
npm: '8.18.0',
node: '18.7.0',

**Comment by MrBartusek** [comment]
Yeah something is broken on node 17 and 18 just downgrade to LTS 16

**Comment by SiriosDev** [comment]
I'll try

**Comment by SiriosDev** [comment]
Now it's working, but I have a question, what is meant by alert swiper? a weather condition or one is function of the card? In a nutshell swiper means swiping your finger (or something else)?

**Comment by MrBartusek** [comment]
This thing

![swiper](https://user-images.githubusercontent.com/23432278/173260942-f597b324-5f52-4e05-9486-88a0530c07cb.gif)

**Comment by SiriosDev** [comment]
oh, nice, then I have a translation! Thank You.

**Comment by MrBartusek** [comment]
I'll close that, let me know when you have any more issues.
