### ISSUE TITLE
Rework card scaling

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/MeteoalarmCard#117]
Since https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v1.7.0 card scaling feature is generating a lot of confusion. Users are confused about why headlines are different on mobile devices or why their cards are not displaying actual headlines from integration, This feature is in desperate need of rework and clarification. I guess implementing these things will improve it a lot.

- Add the ability to disable or change the mode of card scaling via configuration and visual config. There should be a dropdown with options 
	- `Disabled`
	- `Headline only`
	- `Size only`
	- `Headline + size (default)`
- Card should also try to reduce the headline size by a couple of pixels to fit the headline before switching to another one if the size is enabled by configuration options, that's what new size options mean
- There should be a clarification to scaling and override headline how it works exactly to reduce confusion, maybe even fit these configuration options into one section.

**Comment by MrBartusek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Meteoalarm Card Scaling 2.0](https://trello.com/c/edemap4b/3-meteoalarm-card-scaling-20)

**Comment by JN-Jones** [comment]
This is really needed, especially for NINA warnings the headings are nearly never shown
