### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'translationKey')

### ISSUE THREAD

**Issue by dschido** [MrBartusek/MeteoalarmCard#119]
### Describe the bug

Today I got this Error on my Meteo Card:

TypeError: Cannot read properties of undefined (reading 'translationKey')
name: Meteoalarm
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.dwd_weather_warnings_advance_warning_level
  - entity: sensor.dwd_weather_warnings_current_warning_level
override_headline: false

As I did no changes, I suggest, that it depends to the current alerts.
I checked the code, and I think it depends to the dwd level **4**
Is this correct for level 4?
https://github.com/MrBartusek/MeteoalarmCard/blob/b14cda9bfbc16a96d13459a8d6df4737c213e980/src/integrations/dwd.ts#L137-L140
I then changed state and state attibutes from level 4 to level 3 and the card works again.

Here are the Attributs of the current warnings:

attribution: Data provided by DWD
region_name: Nürnberg-Östliche Außenstadt
region_id: 709564010
last_update: '2022-08-26T15:12:03.464000+00:00'
warning_count: 1
warning_1_name: SCHWERES GEWITTER mit EXTREM HEFTIGEM STARKREGEN und HAGEL
warning_1_type: 95
warning_1_level: 4
warning_1_headline: >-
  Amtliche UNWETTERWARNUNG vor SCHWEREM GEWITTER mit EXTREM HEFTIGEM STARKREGEN
  und HAGEL
warning_1_description: >-
  Es treten örtlich Gewitter auf. Dabei gibt es extrem heftigen Starkregen mit
  Niederschlagsmengen bis 60 l/m² in kurzer Zeit sowie Sturmböen mit
  Geschwindigkeiten bis 85 km/h (24m/s, 47kn, Bft 9) und Hagel mit Korngrößen um
  2 cm.
warning_1_instruction: >-
  ACHTUNG! Hinweis auf mögliche Gefahren: Bei Blitzschlag besteht Lebensgefahr!
  Vereinzelt können Bäume entwurzelt und Dächer beschädigt werden. Achten Sie
  besonders auf herabstürzende Äste, Dachziegel oder Gegenstände. Überflutungen
  von Kellern und Straßen sowie örtliche Überschwemmungen an Bächen und kleinen
  Flüssen sind möglich (Details: www.hochwasserzentralen.de). Es können zum
  Beispiel Erdrutsche auftreten. Schließen Sie alle Fenster und Türen! Sichern
  sie Gegenstände im Freien! Halten Sie insbesondere Abstand von Bäumen,
  Gerüsten und Hochspannungsleitungen! Vermeiden Sie möglichst den Aufenthalt im
  Freien!
warning_1_start: '2022-08-26T13:53:00+00:00'
warning_1_end: '2022-08-26T16:00:00+00:00'
warning_1_parameters:
  occurrence: localised
  gusts: <85 [km/h]
  precipitation: <60 [l/m²]
  hail: ~2 [cm]
warning_1_color: '#880e4f'
warning_1:
  start_time: '2022-08-26T13:53:00+00:00'
  end_time: '2022-08-26T16:00:00+00:00'
  event: SCHWERES GEWITTER mit EXTREM HEFTIGEM STARKREGEN und HAGEL
  event_code: 95
  headline: >-
    Amtliche UNWETTERWARNUNG vor SCHWEREM GEWITTER mit EXTREM HEFTIGEM
    STARKREGEN und HAGEL
  description: >-
    Es treten örtlich Gewitter auf. Dabei gibt es extrem heftigen Starkregen mit
    Niederschlagsmengen bis 60 l/m² in kurzer Zeit sowie Sturmböen mit
    Geschwindigkeiten bis 85 km/h (24m/s, 47kn, Bft 9) und Hagel mit Korngrößen
    um 2 cm.
  instruction: >-
    ACHTUNG! Hinweis auf mögliche Gefahren: Bei Blitzschlag besteht
    Lebensgefahr! Vereinzelt können Bäume entwurzelt und Dächer beschädigt
    werden. Achten Sie besonders auf herabstürzende Äste, Dachziegel oder
    Gegenstände. Überflutungen von Kellern und Straßen sowie örtliche
    Überschwemmungen an Bächen und kleinen Flüssen sind möglich (Details:
    www.hochwasserzentralen.de). Es können zum Beispiel Erdrutsche auftreten.
    Schließen Sie alle Fenster und Türen! Sichern sie Gegenstände im Freien!
    Halten Sie insbesondere Abstand von Bäumen, Gerüsten und
    Hochspannungsleitungen! Vermeiden Sie möglichst den Aufenthalt im Freien!
  urgency: immediate
  level: 4
  parameters:
    occurrence: localised
    gusts: <85 [km/h]
    precipitation: <60 [l/m²]
    hail: ~2 [cm]
  color: '#880e4f'
icon: mdi:close-octagon-outline
friendly_name: DWD-Weather-Warnings Current Warning Level

### Card version

v2.1.0

### Integration type

Deutscher Wetterdienst (DWD)

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.dwd_weather_warnings_current_warning_level
  - entity: sensor.dwd_weather_warnings_advance_warning_level
override_headline: false

```

### Integration Configuration

```yaml
[PASTE CONFIGURATION HERE]
```

**Comment by MrBartusek** [comment]
Does this only happen on level 4?

**Comment by dschido** [comment]
Yes, only on level 4. 

As this level is dwd exclusive. I think the code should be:
return level == 4 ? 3 : level?

**Comment by MrBartusek** [comment]
@dschido yup

**Comment by MrBartusek** [comment]
This will be fixed in the next release of the card. Thanks for the report!

Did you actually get that hard thunderstorms past week? We've got only some yellow or orange alerts in Poland.

**Comment by dschido** [comment]
Yes, we had very heavy rain with 50 mm Rain within 1 hour.
But it was the first time I use your very nice card.

Thank you for fixing.
