### ISSUE TITLE
Support for Enviroment of Canada Advisory alerts

### ISSUE THREAD

**Issue by Woodcat64** [MrBartusek/MeteoalarmCard#127]
**Is your feature request related to a problem? Please describe.**

Support for Enviroment of Canada Advisory alerts like Fog or Frost

**Describe the solution you'd like**

To have the card support 4th entity

**Additional context**

![Screenshot 2022-11-24 103214](https://user-images.githubusercontent.com/50119854/203903580-83c538aa-5843-4d81-ac1b-0041a376f4cc.png)
![Screenshot 2022-09-29 124146](https://user-images.githubusercontent.com/50119854/203903593-095bc310-27ab-46fb-9358-fdcef8a03ce1.png)

**Comment by MrBartusek** [comment]
Hey, while developing integration for env Canada i was actually using their [alerts website](https://weather.gc.ca/warnings/index_e.html) for testing and debugging. This website only shows warnings watches and statements so I'm not sure how I should handle alerts from the advisory entity. They are not showing up on the website so i don't see a way to properly develop an integration for them. 

![image](https://user-images.githubusercontent.com/23432278/204081920-71fca2eb-4252-4164-9df3-53d88f05df8e.png)

**Comment by Woodcat64** [comment]
Could they be handled same way as warnings watches and statements?
Env Canada integration creates sensors for each, including the advisories with attributes `alert_1`, `alert_2`, and so on.

**Comment by MrBartusek** [comment]
> Could they be handled same way as warnings watches and statements? Env Canada integration creates sensors for each, including the advisories with attributes `alert_1`, `alert_2`, and so on.

Yeah but I'm unable to debug them and I won't be pushing untested code

**Comment by Woodcat64** [comment]
Understandable. No problem, I just thought I'll ask.

**Comment by MrBartusek** [comment]
I've just noticed that advisories are treated as statement, this will be added

![image](https://user-images.githubusercontent.com/23432278/204375281-5dbb9cfa-029e-4fbb-9894-f60dc7e9b5d0.png)
