### ISSUE TITLE
Better NINA card

### ISSUE THREAD

**Issue by JbbDE** [MrBartusek/MeteoalarmCard#138]
**Is your feature request related to a problem? Please describe.**
The Meteoalarm Card only shows warning Grades  for the Nina Integration.

**Describe the solution you'd like**
It should show Attributes like headline as the main info and if wanted also the description as it's most times more relevant.
**Additional context**
![Screenshot_2022-12-18-21-13-48-24_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/70019640/208317338-7bce3ae3-a5d0-47a4-8a62-01979ed043c3.jpg)

**Comment by MrBartusek** [comment]
Hey, Thanks for creating an issue! To help you with this I need more information like:
- Screenshot from your browser developer console
- Screenshot of rendered card
- Your card configuration YAML
- Your integration configuration YAML

**Comment by JbbDE** [comment]
It's just the downloaded version from HACS
![Screenshot_2022-12-18-21-36-30-33_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/70019640/208318237-4a7cd98f-0576-4c8b-b0d8-7db8538854b9.jpg)
![Screenshot_2022-12-18-21-36-03-26_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/70019640/208318238-115a0e7f-d56a-42a4-9b02-22dc28d9759c.jpg)

**Comment by MrBartusek** [comment]
Yeah, so since you are on mobile the current headline is just too long to fit on the card and it fall backs to this one. This behaviour can be customized by changing the `scaling_mode`. You can see [scaling-mode.md](https://github.com/MrBartusek/MeteoalarmCard/blob/master/dosc/scaling-mode.md) for more info

**Comment by JbbDE** [comment]
The scaling mode doesn't change this behavior even on PC

**Comment by MrBartusek** [comment]
Can you send image how the card looks with disabled scaling mode and attributes that you can see by clicking on the card?

**Comment by JbbDE** [comment]
Sorry, just found out: `override_headline: true` was the problem. Really sorry for waisting your time :(

**Comment by MrBartusek** [comment]
@JbbDE No problem, happy to help!
