### ISSUE TITLE
Show Description-Attribute of NINA Warnings below Headline

### ISSUE THREAD

**Issue by RoepLuke** [MrBartusek/MeteoalarmCard#139]
**Is your feature request related to a problem? Please describe.**
When using the NINA Integration and the Alert contains a Description you have to tap on the Card to show the state of the Entity/Sensor, open the 'Attributes' Drawer and then you can read the Description. This Descriprion can usuallly be between 10 and up to a hundred Words long and is vital Information (contains Evacuation-Radius when a WWII Bomb is found, etc).

**Describe the solution you'd like**
A Switch in the Card configuration to enable showing the Description below the Headline (in a mutch smaller fontsize). In the best case the Description uses the currently empty space of the Card and expands the card vertically only if necessary.

**Additional context**
I'll add further screenshots showing what i've described above but the warning that brought me here is already gone.

**Comment by MrBartusek** [comment]
Displaying any more stuff would be just visual clutter. The design goal is for the card to be as minimalistic as possible. Thanks for your input!
