### ISSUE TITLE
not translated status . Awarenes type 12

### ISSUE THREAD

**Issue by Obelixje** [MrBartusek/MeteoalarmCard#142]
### Describe the bug

Today status shown that was not translated

### Steps to reproduce

language: en-GB
category: Met
event: awareness_type=12,awareness_level=2.0
responseType: Monitor
urgency: Future
severity: Moderate
certainty: Likely
effective: 2023-01-11T12:00:00+00:00
onset: 2023-01-13T08:00:00+00:00
expires: 2023-01-13T22:59:59+00:00
senderName: Rijkswaterstaat
headline: Flooding - Warnings for Noord-Brabant - Nederland
description: Increased discharge of the river Meuse due to precipitation in the  Ardennes region in Belgium and in northern France.
instruction: More information: https://www.rijkswaterstaat.nl/water/waterdata-en-waterberichtgeving/waterbericht/index.aspx
web: http://meteoalarm.eu/en-GB/0/0/NL013-Noord-Brabant.html
contact: wmcn-waterkamer@rws.nl
awareness_type: 12; flooding
awareness_level: 2; yellow; Moderate
attribution: Information provided by MeteoAlarm
device_class: safety
friendly_name: meteoalarm

### Screenshots

![image](https://user-images.githubusercontent.com/83656588/212056775-276dbba3-2006-459f-97d9-11ec5f0d12db.png)

### Card version

2.4.1

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

binary_sensor:
  - platform: meteoalarm
    country: "netherlands"
    province: "Noord-Brabant"

### Integration Configuration

binary_sensor:
  - platform: meteoalarm
    country: "netherlands"
    province: "Noord-Brabant"

**Comment by MrBartusek** [comment]
*awareness_type=12,awareness_level=2.0* is headline provided by your local meteo alerts agency. There is not much i can do with that. The only fix I can suggest is turning on `override_headline`
