### ISSUE TITLE
Differentiate between a 'Watch' and a 'Warning'

### ISSUE THREAD

**Issue by drpeppershaker** [MrBartusek/MeteoalarmCard#143]
**Is your feature request related to a problem? Please describe.**
Currently there is a tornado watch in my area. The alarm card shows a red card with the text 'Tornado Warning'. 

A tornado watch and a tornado warning are two _very_ different things.

> Tornado Watch: Be Prepared! Tornadoes are possible in and near the watch area. Review and discuss your emergency plans and check supplies and your safe room. Be ready to act quickly if a warning is issued or you suspect a tornado is approaching. Acting early helps to save lives! Watches are issued by the [Storm Prediction Center](http://www.spc.noaa.gov/) for counties where tornadoes may occur. The watch area is typically large, covering numerous counties or even states.

>Tornado Warning: Take Action! A tornado has been sighted or indicated by weather radar. There is imminent danger to life and property. Move to an interior room on the lowest floor of a sturdy building. Avoid windows. If in a mobile home, a vehicle, or outdoors, move to the closest substantial shelter and protect yourself from flying debris. Warnings are issued by your [local forecast office](https://www.weather.gov/). Warnings typically encompass a much smaller area (around the size of a city or small county) that may be impacted by a tornado identified by a forecaster on [radar](https://www.nssl.noaa.gov/education/svrwx101/tornadoes/detection/) or by a [trained spotter](https://www.weather.gov/skywarn/)/law enforcement who is watching the storm.

https://www.weather.gov/safety/tornado-ww

**Describe the solution you'd like**
I would like the text on the alarm card to display the appropriate information. Tornado Watch vs Tornado Warning.

**Additional context**

**Comment by MrBartusek** [comment]
These should be displayed as two separate events, please create a [bug report](https://github.com/MrBartusek/MeteoalarmCard/issues/new?assignees=&labels=bug&template=bug_repport.yaml)
