### ISSUE TITLE
Add tap actions

### ISSUE THREAD

**Issue by CumpsD** [MrBartusek/MeteoalarmCard#149]
**Is your feature request related to a problem? Please describe.**
I would like to allow a tap action to navigate to a url

**Describe the solution you'd like**
Support tap actions

**Comment by raetha** [comment]
In case you weren’t aware, this card supports tap actions. I use one along with browser_mod to open a pop up to display the alert descriptions. You just have to edit the card in yaml and add a tap action section.

I’m assuming you might be looking for tap action support in the UI. Which would be handy, though also likely complex.

**Comment by CumpsD** [comment]
Thanks, wasn't aware!

```
tap_action:
  action: url
  url_path: https://www.meteo.be/nl/weer/waarschuwingen/overzichtskaart-belgie
```
