### ISSUE TITLE
Unambiguous wording on the card

### ISSUE THREAD

**Issue by attila123456** [MrBartusek/MeteoalarmCard#15]
**Is your feature request related to a problem? Please describe.**
This might be nitpicking but the current wording of the (English) cards is a bit weird, for example "Yellow Fog Warning" which suggests that there's a warning in effect because of a yellow fog out there.

**Describe the solution you'd like**
A simple change in word order would solve this, e.g.: "Yellow Warning: Fog", or alternatively without the "Yellow Warning" text since the card itself is yellow, indicating the warning level already.

**Comment by MrBartusek** [comment]
You have a point that `Yellow fog warning` isn't great but `Yellow warning: Fog` isn't good either. I want to keep alert on the card to feel like a sentence.  I also thought about switching from colours to severities like `Moderate` `Severe` and `Extreme`. Some countries do that, but I think that colours are easier to understand for end-user.  The solution might be to do something like `Yellow warning for fog`. Maybe it is better grammatically but it seems harder to understand than the current one.

**Comment by attila123456** [comment]
What if it's displayed on two lines, e.g.:

![fog](https://user-images.githubusercontent.com/11088491/118969772-c0135b80-b96d-11eb-876c-4ebf83c70fbd.png)

**Comment by MrBartusek** [comment]
@attila123456 The goal of this card is to make it as simple as possible and it just makes it more cluttered

**Comment by attila123456** [comment]
Ok no prob, thanks.
