### ISSUE TITLE
The card does not show the description of the warning

### ISSUE THREAD

**Issue by karloslb** [MrBartusek/MeteoalarmCard#154]
**Is your feature request related to a problem? Please describe.**
The DWD entity contains a description of the warning - see screenshoot. 
Unfortunately I can't display the description.

**Describe the solution you'd like**
Please add this option.

**Additional context**
![grafik](https://user-images.githubusercontent.com/118773569/216789104-c8348ee7-7146-410c-a35a-15700af2b2a1.png)

**Comment by MrBartusek** [comment]
Hey, thanks for creating an issue. Alerts descriptions are too long to display on the card. We limit ourselves to display only the headline of the warnings on the card. There is not space to show the description on the card.
