### ISSUE TITLE
v2.5.1 - Error: Unknown weatheralerts alert level: Rip Current Statement

### ISSUE THREAD

**Issue by Bazl624** [MrBartusek/MeteoalarmCard#183]
### Describe the bug

card states Error: Unknown weatheralerts alert level: Rip Current Statement

### Screenshots

<img width="463" alt="Screenshot 2023-06-02 at 2 00 54 PM" src="https://github.com/MrBartusek/MeteoalarmCard/assets/102373146/c75c0830-25a8-4249-9160-805d120ac3ea">

### Card version

2.5.1

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-cardentities:  - entity: sensor.santa_rosa_coastalintegration: weatheralertshide_when_no_warning: truescaling_mode: headline_and_scaleoverride_headline: false

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

**Comment by MrBartusek** [comment]
Thank you for pointing that out!
