### ISSUE TITLE
No localization in Russian and Ukrainian.

### ISSUE THREAD

**Issue by polkovnichenko** [MrBartusek/MeteoalarmCard#188]
**Is your feature request related to a problem? Please describe.**
No localization in Russian and Ukrainian.

**Describe the solution you'd like**
I am using HA with ukrainian and russian interface with burze_dzis_net integration and want to suggest adding ru and ua languages to the environment. Made a translation into ru and ua:

[ru.zip](https://github.com/MrBartusek/MeteoalarmCard/files/11712747/ru.zip)
[ua.zip](https://github.com/MrBartusek/MeteoalarmCard/files/11712770/ua.zip)

**Comment by MrBartusek** [comment]
Hey you actually need to submit that thought pull request
