### ISSUE TITLE
Error: Unknown weatheralerts alert level: Special Weather Statement

### ISSUE THREAD

**Issue by justinmbrock** [MrBartusek/MeteoalarmCard#189]
### Describe the bug

The card states Error: Unknown weatheralerts alert level: Special Weather Statement

### Integration state attributes

alert_id: urn:oid:2.49.0.1.840.0.9d1faa050d4d9d6c6b4475edbcf954cc8e5620db.001.1
alert_event: Special Weather Statement
alert_area: Hudson; Eastern Essex; Eastern Union; Richmond (Staten Is.)
alert_NWSheadline: >-
  A STRONG THUNDERSTORM WILL IMPACT PORTIONS OF SOUTHEASTERN UNION, SOUTHEASTERN
  ESSEX, RICHMOND, AND HUDSON COUNTIES THROUGH 100 PM
alert_description: |-
  At 1214 PM EDT, Doppler radar was tracking a developing strong
  thunderstorm over Edison, or near New Brunswick, moving northeast at
  30 mph.

  HAZARD...Winds in excess of 40 mph and pea size hail.

  SOURCE...Radar indicated.

  IMPACT...Gusty winds could knock down tree limbs and blow around
  unsecured objects. Minor damage to outdoor objects is
  possible.

  This strong thunderstorm will be near...
  Linden around 1235 PM EDT.
  Elizabeth and Port Richmond around 1245 PM EDT.
  Newark and Bayonne around 1250 PM EDT.
  Jersey City, Harrison and Kearny around 1255 PM EDT.
  Battery Park around 100 PM EDT.

  Other locations impacted by this storm include Roselle, Rahway, East
  Newark and Heartland Village.
alert_messageType: Alert
alert_status: Actual
alert_category: Met
alert_urgency: Expected
alert_severity: Moderate
alert_certainty: Observed
alert_response: Execute
alert_instruction: |-
  This storm may intensify, so be certain to monitor local radio
  stations and available television stations for additional information
  and possible warnings from the National Weather Service.
alert_sent: '2023-06-14T12:15:00-04:00'
alert_effective: '2023-06-14T12:15:00-04:00'
alert_onset: '2023-06-14T12:15:00-04:00'
alert_expires: '2023-06-14T13:00:00-04:00'
alert_title: Special Weather Statement issued June 14 at 12:15PM EDT
display_title: Special Weather Statement issued June 14 at 12:15PM EDT
alert_zoneid: NJZ105,NJC013
display_message: >-
  A STRONG THUNDERSTORM WILL IMPACT PORTIONS OF SOUTHEASTERN UNION, SOUTHEASTERN
  ESSEX, RICHMOND, AND HUDSON COUNTIES THROUGH 100 PM<br>
    
    <br>At 1214 PM EDT, Doppler radar was tracking a developing strong thunderstorm over Edison, or near New Brunswick, moving northeast at 30 mph.

  HAZARD...Winds in excess of 40 mph and pea size hail.

  SOURCE...Radar indicated.

  IMPACT...Gusty winds could knock down tree limbs and blow around unsecured
  objects. Minor damage to outdoor objects is possible.

  This strong thunderstorm will be near... Linden around 1235 PM EDT. Elizabeth
  and Port Richmond around 1245 PM EDT. Newark and Bayonne around 1250 PM EDT.
  Jersey City, Harrison and Kearny around 1255 PM EDT. Battery Park around 100
  PM EDT.

  Other locations impacted by this storm include Roselle, Rahway, East Newark
  and Heartland Village.</ul><br>
    
    This storm may intensify, so be certain to monitor local radio stations and available television stations for additional information and possible warnings from the National Weather Service.<br>
    
    <br>Where : Western Essex
    <br>Effective: 2023-06-14T12:15:00-04:00
    <br>Expires: 2023-06-14T13:00:00-04:00
spoken_title: >-
  Attention!!! Weather alert for Western Essex. A Special Weather Statement
  issued June 14 at 12:15PM EDT. A strong thunderstorm will impact portions of
  southeastern union, southeastern essex, richmond, and hudson counties through
  100 pm.
spoken_message: >-
  At 1214 PM EDT, Doppler radar was tracking a developing strong thunderstorm
  over Edison, or near New Brunswick, moving northeast at 30 mph.

  HAZARD...Winds in excess of 40 mph and pea size hail.

  SOURCE...Radar indicated.

  IMPACT...Gusty winds could knock down tree limbs and blow around unsecured
  objects. Minor damage to outdoor objects is possible.

  This strong thunderstorm will be near... Linden around 1235 PM EDT. Elizabeth
  and Port Richmond around 1245 PM EDT. Newark and Bayonne around 1250 PM EDT.
  Jersey City, Harrison and Kearny around 1255 PM EDT. Battery Park around 100
  PM EDT.

  Other locations impacted by this storm include Roselle, Rahway, East Newark
  and Heartland Village.
    
      This storm may intensify, so be certain to monitor local radio stations and available television stations for additional information and possible warnings from the National Weather Service.
icon: hass:message-alert
friendly_name: Weather Alert 1

### Screenshots

![Screenshot_20230614-121158~2](https://github.com/MrBartusek/MeteoalarmCard/assets/6379307/5a2b2d6f-94f6-421a-89ed-52bdf9b913a3)

### Card version

v2.5.1

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: sensor.weatheralerts_1
integration: weatheralerts
override_headline: false
hide_when_no_warning: false
scaling_mode: headline_and_scale
disable_swiper: false

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

sensor:
  - platform: weatheralerts
    state: NJ
    zone: 105
    county: 13

**Comment by MrBartusek** [comment]
Hey that was fixed in #186 it will be part of next update
