### ISSUE TITLE
Doesnt seem to know how to handle Beach Warnings

### ISSUE THREAD

**Issue by chrkov** [MrBartusek/MeteoalarmCard#190]
### Describe the bug

I have an active alert for a beach hazard and it looks like you dont understand that type of warning.   I am using this with Weatheralerts integration.

### Integration state attributes

alerts: 
- area: Lake; Northern Cook; Central Cook; Lake; Porter
  certainty: Likely
  description: |-
    * WHAT...High wave action and dangerous currents expected at Lake
    Michigan beaches. Waves 3 to 6 ft.

    * WHERE...In Illinois, Lake, Northern Cook and Central Cook
    Counties. In Indiana, Lake and Porter Counties.

    * WHEN...From Thursday afternoon through Friday morning.

    * IMPACTS...Swimming conditions will be life threatening,
    especially for inexperienced swimmers. For information on swim
    advisories or bans at Chicago beaches: www. cpdbeaches. com.
  ends: '2023-06-16T10:00:00-05:00'
  event: Beach Hazards Statement
  instruction: |-
    Remain out of the water to avoid dangerous swimming conditions
    and do not venture out onto piers, jetties, breakwalls, or other
    shoreline structures.
  response: Avoid
  sent: '2023-06-14T14:59:00-05:00'
  severity: Moderate
  title: >-
    Beach Hazards Statement issued June 14 at 2:59PM CDT until June 16 at
    10:00AM CDT
  urgency: Expected
  NWSheadline:
    - >-
      BEACH HAZARDS STATEMENT IN EFFECT FROM THURSDAY AFTERNOON THROUGH FRIDAY
      MORNING
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-06-14T14:59:00-05:00'
  expires: '2023-06-14T23:00:00-05:00'
  endsExpires: '2023-06-16T10:00:00-05:00'
  onset: '2023-06-15T12:00:00-05:00'
  status: Actual
  messageType: Alert
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Chicago IL
  id: urn:oid:2.49.0.1.840.0.c591c8652471864692cb454cdb7406fe163846dc.001.1
  zoneid: INZ001,INC089

integration: weatheralerts
state: IN
zone: INZ001,INC089
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Lake

### Screenshots

![Screenshot 2023-06-14 175244](https://github.com/MrBartusek/MeteoalarmCard/assets/57808614/1b2e788b-213e-4e0a-bf25-30f554a3d72a)

### Card version

2.5.1

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: sensor.lake
integration: weatheralerts
override_headline: false
disable_swiper: false

### Integration type

Meteoalarm

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

sensor:
  - platform: weatheralerts
    state: IN
    zone: 001
    county: 089

**Comment by MrBartusek** [comment]
Hey that was fixed in #186 it will be part of next update

**Comment by chrkov** [comment]
That was quick.  Thanks!

**Comment by chrkov** [comment]
Hi,
Looks like there is a "Beach Hazards" also.   Can you add that as well.   I am seeing this today.
![image](https://github.com/MrBartusek/MeteoalarmCard/assets/57808614/0d7b8983-82c0-4ac8-a493-3db1664f7d0f)

**Comment by MrBartusek** [comment]
#197
