### ISSUE TITLE
Compatibility for météo France île de la Réunion

### ISSUE THREAD

**Issue by dth97410** [MrBartusek/MeteoalarmCard#192]
Hello, I'd like to suggest compatibility if possible with météo France and overseas departments. I live on Reunion Island and unfortunately it's not possible to get weather alerts via this integration. Knowing that we can have quite frequent alerts from météo

**Comment by MrBartusek** [comment]
Hey please provide url to this integration

**Comment by dth97410** [comment]
> https://www.home-assistant.io/integrations/meteo_france

I think it's because my region isn't in mainland France but in a French overseas territory, and the weather monitoring is managed by Météo France. The domain name of the météo France website is https://meteofrance.com/ and that of my region is https://meteofrance.re/fr

**Comment by MrBartusek** [comment]
@dth97410 I think you are in the wrong place. This is the repository for MeteoalarmCard which is a frontend card displaying alerts provided via integrations. It has nothing to do with providing alerts. I think you should request changes to underlying meteo-france integrations to https://github.com/home-assistant/core
