### ISSUE TITLE
Option to display all warnings at once

### ISSUE THREAD

**Issue by Loman0815** [MrBartusek/MeteoalarmCard#193]
**Is your feature request related to a problem? Please describe.**
When displaying the card on an info dashboard and you have multiple warning, there is only one warning shown. With 'disable_swiper = false' you always have to actively check what the other warnings are.

**Describe the solution you'd like**
Option to display all the warnings at once on a row based basis instead of the need to swipe throuhg all the warnings, e. g. 'show_all_warnings' = true

**Comment by MrBartusek** [comment]
> Option to display all the warnings at once on a row-based basis instead of the need to swipe through all the warnings, e. g. 'show_all_warnings' = true

Integrations can provide a virtually unlimited number of alerts so if they were to be displayed on a row-basis the card would be able to have unlimited height, which will for sure break the UI.

**Comment by Loman0815** [comment]
Yeah i do understand that. From my experience (but i can only talk from my location) there is only a maximum of three or four warnings at the same time.

Maybe showing all warnings at once can lead to another parameter like 'number_of_warnings' which than, in combination with the possibility to show the warnings row based, only shows for example the four latest warnings.

**Comment by MrBartusek** [comment]
Hey! I've thought about that one. The problem with this request is that it's a major design change to the current card. I don't plan to support multiple layouts display modes and such. This would require to another configuration option for another display mode and would require maintaining it too! I can't allow that. I'll now close this issue, thank you for your contribution!
