### ISSUE TITLE
'Beach Hazards' Unknown

### ISSUE THREAD

**Issue by chrkov** [MrBartusek/MeteoalarmCard#197]
### Describe the bug

I reported a "Beach Hazards Statement" issue a couple weeks ago.  Looks like there is a "Beach Hazards" also that the card doesn't understand.

### Integration state attributes

alerts: 
- area: Lake; Porter; Newton; Jasper
  certainty: Unknown
  description: |-
    An Air Quality Action Day has been forecast for Northwest Indiana
    for elevated ozone levels and wildfire smoke, and is in effect from
    midnight tonight to midnight CDT Tuesday night.

    Ozone Levels are expected to be at unhealthy levels for sensitive
    groups. For additional information...please visit the IDEM SMOG
    Watch web site at www.SmogWatch.IN.gov or the EPA AIRNOW web site at
    www.airnow.gov and click on Indiana.
  ends: null
  event: Air Quality Alert
  instruction: null
  response: Monitor
  sent: '2023-06-26T14:38:00-05:00'
  severity: Unknown
  title: Air Quality Alert issued June 26 at 2:38PM CDT
  urgency: Unknown
  NWSheadline:
    - >-
      AIR QUALITY ALERT IN EFFECT FROM MIDNIGHT TONIGHT TO MIDNIGHT CDT TUESDAY
      NIGHT
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-06-26T14:38:00-05:00'
  expires: '2023-06-28T00:00:00-05:00'
  endsExpires: '2023-06-28T00:00:00-05:00'
  onset: '2023-06-26T14:38:00-05:00'
  status: Actual
  messageType: Alert
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Chicago IL
  id: urn:oid:2.49.0.1.840.0.48d9c318f9ce9385c42c16205e904af28df145ac.001.1
  zoneid: INZ001,INC089
- area: Lake; Porter
  certainty: Likely
  description: |-
    * WHAT...High wave action and dangerous currents expected at
    Lake Michigan beaches. Waves 4 to 7 ft expected.

    * WHERE...Lake IN and Porter Counties.

    * WHEN...From 1 AM CDT Tuesday through late Tuesday night.

    * IMPACTS...Swimming conditions will be life threatening,
    especially for inexperienced swimmers.
  ends: '2023-06-28T01:00:00-05:00'
  event: Beach Hazards Statement
  instruction: |-
    Remain out of the water to avoid dangerous swimming conditions
    and do not venture out onto piers, jetties, breakwalls, or other
    shoreline structures.
  response: Avoid
  sent: '2023-06-26T21:08:00-05:00'
  severity: Moderate
  title: >-
    Beach Hazards Statement issued June 26 at 9:08PM CDT until June 28 at 1:00AM
    CDT
  urgency: Expected
  NWSheadline:
    - >-
      BEACH HAZARDS STATEMENT REMAINS IN EFFECT FROM 1 AM CDT TUESDAY THROUGH
      LATE TUESDAY NIGHT
  hailSize: 'null'
  windGust: 'null'
  waterspoutDetection: 'null'
  effective: '2023-06-26T21:08:00-05:00'
  expires: '2023-06-27T05:15:00-05:00'
  endsExpires: '2023-06-28T01:00:00-05:00'
  onset: '2023-06-27T01:00:00-05:00'
  status: Actual
  messageType: Update
  category: Met
  sender: w-nws.webmaster@noaa.gov
  senderName: NWS Chicago IL
  id: urn:oid:2.49.0.1.840.0.47dc706eb4cbeaf3909023daf6ad0dffaa38fee8.001.1
  zoneid: INZ001,INC089

integration: weatheralerts
state: IN
zone: INZ001,INC089
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Lake

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/57808614/4b880b49-07b2-4653-9f87-d27b30768c6b)

### Card version

2.5.2

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

 - type: custom:meteoalarm-card
    entities:
      - entity: sensor.lake
    integration: weatheralerts
    override_headline: false
    disable_swiper: false
    hide_when_no_warning: true

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

platform: weatheralerts
state: IN
zone: 001
county: 089

**Comment by MrBartusek** [comment]
It seems like i forgot to push these changes in #186, sorry for that

**Comment by chrkov** [comment]
LOL.   It happens...
