### ISSUE TITLE
Card not displayed

### ISSUE THREAD

**Issue by mfabiani53** [MrBartusek/MeteoalarmCard#2]
**Describe the bug**
The card is not displayed in the UI.
In the console of the browser i get this:

![Schermata 2021-05-16 alle 11 23 09](https://user-images.githubusercontent.com/37701688/118392334-76f39c80-b639-11eb-95b8-499014d56bcb.png)

**Comment by MrBartusek** [comment]
Hey, thanks for the report! Could you send a screenshot with attributes of meteoalarm entity from the `Developer Tools` tab?

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by mfabiani53** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/37701688/118395271-ab6f5480-b649-11eb-81cd-9ca4318954fc.png)

**Comment by mfabiani53** [comment]
I am using the custom component meteoalarmeu
https://github.com/xlcnd/meteoalarmeu

**Comment by MrBartusek** [comment]
> I am using the custom component meteoalarmeu
> [xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu)

Okay so that would resolve the issue, as of now, [xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu) is not supported, only [the core one is](https://www.home-assistant.io/integrations/meteoalarm/). Moving this to -> #4

**Comment by mfabiani53** [comment]
You advice me to switch the the core one, or wait an update which support also the meteoalarmeu?

**Comment by MrBartusek** [comment]
> You advice me to switch the the core one, or wait an update which support also the meteoalarmeu?

If you have any automations or other things relying on `meteoalarmeu` you can just keep it as it is and add core integration as a separate entity. That way you can use `binary_sensor.meteoalarmeu` as you would before and point card to `binary_sensor.meteoalarm` instead

**Comment by mfabiani53** [comment]
Problem is that the core integration and the custom one use both the same platform.
I have this in binary sensor:

```
- platform: meteoalarm
  name: 'Allarme Meteo Abruzzo'
  language: 'it'
  country: 'IT'
  province: 'Abruzzo'
```
And it's the same if i want to use the core integration.... 
I hope you can update the card asap so i can use it independently from the integration...
