### ISSUE TITLE
Half dutch translation ?

### ISSUE THREAD

**Issue by Tyrian81** [MrBartusek/MeteoalarmCard#20]
It seems i'm somehow stuck at a half dutch translation is it not yet fully translated, see picture ?

![image](https://user-images.githubusercontent.com/31477524/119151469-b4986100-ba4f-11eb-92ec-d1c62367c991.png)

**Comment by BartEngelen** [comment]
What do you mean with half translation ?
The card is in dutch see my screenshot.
![image](https://user-images.githubusercontent.com/17978789/119154328-58830c00-ba52-11eb-85ce-f8fb77b6be89.png)

**Comment by MrBartusek** [comment]
The card is fully translated to Dutch, you probably didn't configure language in meteoalarm integration  and it defaulted to English. https://www.home-assistant.io/integrations/meteoalarm/#language 

Let me know if that fixes the issue

**Comment by Tyrian81** [comment]
binary_sensor:
  - platform: meteoalarm
    country: "NL"
    language: "ne"
    province: "Drenthe"


and my card :
type: 'custom:meteoalarm-card'
entity: binary_sensor.meteoalarm
country: nl

its set to dutch i assume ,yet the card is giving

**Comment by MrBartusek** [comment]
For some reason Netherlands issues `event` in English when they are not supposed to.
![image](https://user-images.githubusercontent.com/23432278/119160511-a733a480-ba58-11eb-95d4-b76ca1cb7d31.png)

This is not an issue caused by the card, there will be an option to override this in the future but, as of now, there is not

**Comment by Tyrian81** [comment]
> What do you mean with half translation ?
> The card is in dutch see my screenshot.
> ![image](https://user-images.githubusercontent.com/17978789/119154328-58830c00-ba52-11eb-85ce-f8fb77b6be89.png)

Is it possible to view your card and config.yaml entry ?
Yours seems to be working fine ?

**Comment by BartEngelen** [comment]
Binary Sensor:n
- platform: meteoalarm
  country: "BE"
  province: "Limburg / Limbourg"
 language: nl

Card:
type: 'custom:meteoalarm-card'
entity: binary_sensor.meteoalarm

**Comment by BartEngelen** [comment]
Binary Sensor:
- platform: meteoalarm
   country: "BE"
   province: "Limburg / Limbourg"

Card:
type: 'custom:meteoalarm-card'
entity: binary_sensor.meteoalarm

I get this result:
![image](https://user-images.githubusercontent.com/17978789/119166511-fed50e80-ba5e-11eb-9dfe-2143f00ea8e8.png)

Binary Sensor:
- platform: meteoalarm
  country: "BE"
  province: "Limburg / Limbourg"
  language: nl

Card:
type: 'custom:meteoalarm-card'
entity: binary_sensor.meteoalarm

I get this result:
![image](https://user-images.githubusercontent.com/17978789/119167073-af431280-ba5f-11eb-82e3-60a56fc87951.png)

It seems also very strange to me now !
