### ISSUE TITLE
"Special Weather" Alert Type Not Found

### ISSUE THREAD

**Issue by ElementVoid** [MrBartusek/MeteoalarmCard#206]
### Describe the bug

Card does not recognize special weather statements from weatheralerts integration.

Error: Unknown weatheralerts alert type: Special Weather

### Integration state attributes

alerts:
  - area: Pinal, AZ
    certainty: Unknown
    description: |-
      The Pinal County Department of Air Quality has issued a PM-10 High
      Pollution Advisory for Pinal County including Apache Junction, Casa
      Grande, Coolidge, and Florence on Sunday.

      An episode of strong and gusty winds is forecast to generate
      widespread blowing dust that may result in local PM-10 concentrations
      that pose a health risk. Adverse health effects increase as air
      quality deteriorates.

      Coarse particulate matter - also known as PM-10 - is an air
      contaminant that can aggravate heart and lung disease conditions,
      especially in older adults, children, and those with asthma. A
      decrease in physical activity is recommended.

      Consolidate your travel, stabilize loose soils, slow down or avoid
      travel on dirt roads, reduce or eliminate fireplace use, and avoid
      using gas-powered lawn equipment.

      For details on this High Pollution Advisory for Pinal County, visit
      the Pinal County Department of Air Quality internet site at
      https://www.pinalcountyaz.gov/AirQuality/Documents/Forecast/
      aqforecast.pdf
    ends: null
    event: Air Quality Alert
    instruction: null
    response: Monitor
    sent: '2023-07-28T09:26:00-07:00'
    severity: Unknown
    title: Air Quality Alert issued July 28 at 9:26AM MST
    urgency: Unknown
    NWSheadline:
      - PM-10 HIGH POLLUTION ADVISORY FOR PINAL COUNTY SUNDAY
    hailSize: 'null'
    windGust: 'null'
    waterspoutDetection: 'null'
    effective: '2023-07-28T09:26:00-07:00'
    expires: '2023-07-30T21:00:00-07:00'
    endsExpires: '2023-07-30T21:00:00-07:00'
    onset: '2023-07-28T09:26:00-07:00'
    status: Actual
    messageType: Alert
    category: Met
    sender: w-nws.webmaster@noaa.gov
    senderName: NWS Phoenix AZ
    id: urn:oid:2.49.0.1.840.0.451a658b9e36a6ab020828b68345b25199af94e5.001.1
    zoneid: AZZ553,AZC021
  - area: Tonto Basin; Pinal/Superstition Mountains; San Carlos; Globe/Miami
    certainty: Observed
    description: |-
      At 429 PM MST, Doppler radar was tracking a strong thunderstorm near
      Miami, or near Globe. This storm was nearly stationary.

      HAZARD...Wind gusts up to 50 mph.

      SOURCE...Radar indicated.

      IMPACT...Gusty winds could knock down tree limbs and blow around
      unsecured objects.

      Locations impacted include...
      Globe, Miami, Top Of The World, Central Heights-Midland City,
      Top-Of-The-World, Claypool, and Inspiration.

      This includes the following highways...
      US Highway 60 between mile markers 235 and 253.
      AZ Route 70 between mile markers 253 and 255.
      AZ Route 77 between mile markers 167 and 170.
    ends: null
    event: Special Weather Statement
    instruction: |-
      If outdoors, consider seeking shelter inside a building.

      This storm may intensify, so be certain to monitor local radio
      stations and available television stations for additional information
      and possible warnings from the National Weather Service.
    response: Execute
    sent: '2023-07-29T16:29:00-07:00'
    severity: Moderate
    title: Special Weather Statement issued July 29 at 4:29PM MST
    urgency: Expected
    NWSheadline:
      - >-
        A strong thunderstorm will impact portions of Gila and Pinal Counties
        through 500 PM MST
    hailSize: 'null'
    windGust: 'null'
    waterspoutDetection: 'null'
    effective: '2023-07-29T16:29:00-07:00'
    expires: '2023-07-29T17:00:00-07:00'
    endsExpires: '2023-07-29T17:00:00-07:00'
    onset: '2023-07-29T16:29:00-07:00'
    status: Actual
    messageType: Alert
    category: Met
    sender: w-nws.webmaster@noaa.gov
    senderName: NWS Phoenix AZ
    id: urn:oid:2.49.0.1.840.0.0891f39c70d87a2fbf7088cc8b1ed981b4803f7a.001.1
    zoneid: AZZ553,AZC021
integration: weatheralerts
state: AZ
zone: AZZ553,AZC021
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Northwest Pinal County

### Screenshots

![firefox_xDYrdgcliA](https://github.com/MrBartusek/MeteoalarmCard/assets/94652208/781c00ee-7718-457f-bfa8-eb03eecb36da)

### Card version

v2.5.3

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

      - type: "custom:meteoalarm-card"
        integration: weatheralerts
        entities: sensor.northwest_pinal_county
        override_headline: false
        hide_when_no_warning: false

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

  - platform: weatheralerts
    state: AZ
    zone: 553
    county: 21

**Comment by MrBartusek** [comment]
Are you sure you have updated your card? This was fixed in #198 (`v2.5.3`). Please re-install the card and check which version shows in your browser's developer tools.

**Comment by ElementVoid** [comment]
Was a fresh install today. Never had it installed before. Browser console shows v2.5.3 as well.
![image](https://github.com/MrBartusek/MeteoalarmCard/assets/94652208/37c45d59-46a9-4f71-bb2b-a8b1e5e19923)

**Comment by shaulbd** [comment]
Same issue for me as well today.
