### ISSUE TITLE
Color of the warnings

### ISSUE THREAD

**Issue by joretapo1** [MrBartusek/MeteoalarmCard#207]
Hi,
I find the "Yellow" color alert for "Moderate" most orange than yellow.
I find the black color for "no alert" not fine at all.

Is that possible to have a real yellow for severity "Moderate" ? #ffff7a hex color for example ?
Is that possible to have green color for the "no alert" ?

Thanks a lot.

**Comment by MrBartusek** [comment]
> I find the "Yellow" color alert for "Moderate" most orange than yellow.

It's from HA default css colors

> I find the black color for "no alert" not fine at all.

It's regular card background on dark theme 

> Is that possible to have a real yellow for severity "Moderate" ? #ffff7a hex color for example ?
> Is that possible to have green color for the "no alert" ?

I mean that is a thing that would be best done via tool like card mod but honesty i do not think that is possible, definetly could be a improvment from our side
