### ISSUE TITLE
DWD: Unknown event ID: 248

### ISSUE THREAD

**Issue by jckoester** [MrBartusek/MeteoalarmCard#208]
### Describe the bug

Today's heat warning by DWD does not het displayed, instead error message about unknown event ID. Same warning coming from NINA does not coause any problems.

### Integration state attributes

region_name: Stadt Stuttgart
region_id: 108111000
last_update: 2023-08-14T08:31:47.543000+00:00
warning_count: 2
warning_1_name: STARKE HITZE
warning_1_type: 247
warning_1_level: 1
warning_1_headline: Amtliche WARNUNG vor HITZE
warning_1_description: Am Montag wird eine starke Wärmebelastung erwartet. Am Dienstag wird eine starke Wärmebelastung erwartet. Die Hitze wird alte und pflegebedürftige Menschen extrem belasten. Dienstag ist mit einer zusätzlichen Belastung aufgrund verringerter nächtlicher Abkühlung insbesondere im dicht bebauten Stadtgebiet von Stuttgart zu rechnen. 
warning_1_instruction: Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
warning_1_start: 2023-08-14T09:00:00+00:00
warning_1_end: 2023-08-15T17:00:00+00:00
warning_1_parameters: null
warning_1_color: #cc99ff
warning_1: 
start_time: '2023-08-14T09:00:00+00:00'
end_time: '2023-08-15T17:00:00+00:00'
event: STARKE HITZE
event_code: 247
headline: Amtliche WARNUNG vor HITZE
description: >-
  Am Montag wird eine starke Wärmebelastung erwartet. Am Dienstag wird eine
  starke Wärmebelastung erwartet. Die Hitze wird alte und pflegebedürftige
  Menschen extrem belasten. Dienstag ist mit einer zusätzlichen Belastung
  aufgrund verringerter nächtlicher Abkühlung insbesondere im dicht bebauten
  Stadtgebiet von Stuttgart zu rechnen. 
instruction: >-
  Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer
  Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit
  die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
urgency: immediate
level: 1
parameters: null
color: '#cc99ff'

warning_2_name: EXTREME HITZE
warning_2_type: 248
warning_2_level: 3
warning_2_headline: Amtliche WARNUNG vor EXTREMER HITZE
warning_2_description: Am Montag wird bis zu einer Höhe von 400m eine extreme Wärmebelastung erwartet. 
warning_2_instruction: Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
warning_2_start: 2023-08-14T09:00:00+00:00
warning_2_end: 2023-08-14T17:00:00+00:00
warning_2_parameters: null
warning_2_color: #9e46f8
warning_2: 
start_time: '2023-08-14T09:00:00+00:00'
end_time: '2023-08-14T17:00:00+00:00'
event: EXTREME HITZE
event_code: 248
headline: Amtliche WARNUNG vor EXTREMER HITZE
description: >-
  Am Montag wird bis zu einer Höhe von 400m eine extreme Wärmebelastung
  erwartet. 
instruction: >-
  Hitzebelastung kann für den menschlichen Körper gefährlich werden und zu einer
  Vielzahl von gesundheitlichen Problemen führen. Vermeiden Sie nach Möglichkeit
  die Hitze, trinken Sie ausreichend Wasser und halten Sie die Innenräume kühl.
urgency: immediate
level: 3
parameters: null
color: '#9e46f8'

attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings 108111000 Current Warning Level

### Screenshots

![Screenshot 2023-08-14 103927](https://github.com/MrBartusek/MeteoalarmCard/assets/777345/df805cbe-bbdd-4706-b35f-6e431218ada0)

### Card version

v2.5.3

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entity: sensor.dwd_weather_warnings_current_warning_level
integration: dwd
entities:
  - entity: sensor.dwd_weather_warnings_108111000_advance_warning_level
  - entity: sensor.dwd_weather_warnings_108111000_current_warning_level

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
Hey! Thanks for bringing this up, just a quick question, should this event translate to *High Temperature Warning* right?

**Comment by jckoester** [comment]
More or less, yes. Direct translation would be "EXTREME heat warning", though their definition of 'extreme' seems to be a bit off.
