### ISSUE TITLE
French - Environment Canada - Issue with alert "Veille D'Orages Violents"

### ISSUE THREAD

**Issue by w1zz4** [MrBartusek/MeteoalarmCard#213]
### Describe the bug

There is an issue with the alert " Veille D'Orages Violents " from Environemment Canada. The card is looking for " Veille De " prefix but in that case the prefix is " Veille D' "

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/3812081/1a7b6118-64a0-4197-9451-2434fd99219a)
![image](https://github.com/MrBartusek/MeteoalarmCard/assets/3812081/4f89a6cd-9bf8-4213-a4c7-273842dd5337)

### Card version

 v2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

  - type: custom:meteoalarm-card
    entities:
      - entity: sensor.laval_warnings
      - entity: sensor.laval_watches
      - entity: sensor.laval_statements
      - entity: sensor.laval_advisory

### Integration type

Environnement Canada

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
> The card is looking for " Veille De " prefix but in that case the prefix is " Veille D' "

is this permanent change or it's just specific wording to this type of alert?

**Comment by w1zz4** [comment]
TBH, I don’t know if the behaviour changed because I started uaing it today. Maube they fixed a typo or maybe none noticed it before.For the problem, the case of “de“ vs “d’” is the exact same rule than “a” and “an“ in English. If the first letter of the following word is a vowel it’s “d’” otherwise it’s “de”. So both cases are possible.Thank youÉtienne ***@***.*** Sep 7, 2023, at 19:19, Bartosz Dokurno ***@***.***> wrote:﻿

The card is looking for " Veille De " prefix but in that case the prefix is " Veille D' "

is this permanent change or it's just specific wording to this type of alert?
