### ISSUE TITLE
DWD selected integration doesn't match selected entity

### ISSUE THREAD

**Issue by kineci** [MrBartusek/MeteoalarmCard#214]
### Describe the bug

Can some one take a look at what's wrong?

### Integration state attributes

region_name: Stadt Nordenham
region_id: 803461007
last_update: '2023-09-16T23:32:08.690000+00:00'
warning_count: 0
attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings 803461007 Aktuelle Warnstufe

region_name: Stadt Nordenham
region_id: 803461007
last_update: '2023-09-16T23:47:08.675000+00:00'
warning_count: 0
attribution: Data provided by DWD
icon: mdi:close-octagon-outline
friendly_name: DWD Weather Warnings 803461007 Vorwarnstufe

### Screenshots

![Screenshot (62)](https://github.com/MrBartusek/MeteoalarmCard/assets/78767752/00e88cfc-d377-44c8-b33f-421fcb6c2187)
![Screenshot (60)](https://github.com/MrBartusek/MeteoalarmCard/assets/78767752/126179a5-be76-42ea-87c0-7d2e1d070c8c)

### Card version

2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: sensor.dwd_weather_warnings_803461007_vorwarnstufe
  - entity: sensor.dwd_weather_warnings_803461007_aktuelle_warnstufe
integration: dwd
hide_when_no_warning: false
scaling_mode: headline_and_scale
disable_swiper: false
override_headline: false
hide_caption: false

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI

**Comment by csoltenborn** [comment]
Same problem here. Same configuration as above, but with 105315000 (Stadt Köln) and 705315105 (Köln Nippes).

**Comment by arboeh** [comment]
Same here...

**Comment by kineci** [comment]
I eventually fixed it myself. It's a language issue. Because the entities are created in German by the integration they cannot be recognised.
You have to rename both sensors accordingly. Changing "vorwahnstufe" to "advance_warning_level" and "aktuelle_warnstufe" to "current_warning_level"

So the entities are renamed like they are mentioned in the documentation:

Before:
- sensor.dwd_weather_warnings_vorwahnstufe
- sensor.dwd_weather_warnings_aktuelle_warnstufe

After:
- sensor.dwd_weather_warnings_advanced_warning_level 
- sensor.dwd_weather_warnings_current_warning_level

It's strange, that it's not mentioned in the documentation as dwd will mainly be used by German users, so they will likely encounter the same problem.

**Comment by csoltenborn** [comment]
Thanks a lot, works like a charm! And indeed a strange bug in the sense that it should show up very quickly, and should be easily fixable, so why does it (still) exist? Are we the only ones using it?

Minor comment: in the final names (for me - thanks again ;-) ), you have a typo ("advanced" should be advance as pointed out correctly above). Just for the people who (like me) copy&pasted it :-)

**Comment by MrBartusek** [comment]
> so why does it (still) exist? Are we the only ones using it?

You are free to make PR for that, i have quite limited time recently

**Comment by kineci** [comment]
> Minor comment: in the final names (for me - thanks again ;-) ), you have a typo ("advanced" should be advance as pointed out correctly above). Just for the people who (like me) copy&pasted it :-)

You're right. I've corrected the original comment incase someone's just copies it and thinks it doesn't work :D
