### ISSUE TITLE
Wrong icon on alert

### ISSUE THREAD

**Issue by tbal82** [MrBartusek/MeteoalarmCard#215]
### Describe the bug

Hi,

2 things :

1) In my opinion, alert colors are incorrect : yellow looks orange and orange looks red. I would suggest to replace yellow (#EE5A24) by #FC9708, and orange (#FF9800) by #FFDC00 if others agree

2) I did not notice this issue before, but today is "rain yellow" alert in my city and the icon is alert-circle-outline instead of weather-pooring.

Seems like the awareness_type id is incorrect, as it should be 10 instead of 13 right ?

### Integration state attributes

language: fr-FR
category: Met
event: Vigilance jaune pluie-inondation
responseType: Monitor
urgency: Future
severity: Moderate
certainty: Likely
effective: 2023-09-21T06:00:00+02:00
onset: 2023-09-21T06:04:26+02:00
expires: 2023-09-22T00:00:00+02:00
senderName: METEO-FRANCE
headline: Vigilance jaune pluie-inondation
description: Des phénomènes habituels dans la région mais occasionnellement et localement dangereux sont prévus (exemple : mistral, orage d'été, montée des eaux, fortes vagues submergeant le littoral).
instruction: Soyez attentifs si vous pratiquez des activités sensibles au risque météorologique ou à proximité d'un rivage ou d'un cours d'eau. Tenez-vous au courant de l'évolution de la situation.
web: http://vigilance.meteofrance.com/
contact: METEO-FRANCE
awareness_level: 2; yellow; Moderate
awareness_type: 13; rain-flood
attribution: Information provided by MeteoAlarm
device_class: safety
friendly_name: meteoalarm

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/28534767/3c7f063a-7606-43d7-a501-597dd69ff64e)

### Card version

v2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  entity: binary_sensor.meteoalarm
integration: meteoalarm

### Integration type

Meteoalarm

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
I have no idea which integration you are using. You just specified Meteo France in the title and Meteoalarm in description.

**Comment by tbal82** [comment]
Updated the title to make it less confusing, I am using the meteoalarm integration :)

**Comment by tbal82** [comment]
Hi,

Any update on this ?

**Comment by MrBartusek** [comment]
> Hi,
> 
> Any update on this ?

The issue has been accepted and will be worked on in the future
