### ISSUE TITLE
Meteoalarm: Return multiple warnings

### ISSUE THREAD

**Issue by mdimjasevic** [MrBartusek/MeteoalarmCard#221]
Given how the Meteoalarm integration provides information on only one warning, I was excited to run into the Meteoalarm Card given its promise to deliver multiple warnings when they exist. However, after adding the card to my dashboard and configuring it to rely on Meteoalarm, I see no swiper on the card that would let me jump to the next warning.

It is not so uncommon for multiple warnings to co-exist in a given area. My region currently has two.

This behavior probably comes from here: https://github.com/MrBartusek/MeteoalarmCard/blob/d0ca43500f5f173f3cd6f9a99a92dbeec264cac6/src/integrations/meteoalarm.ts#L36

Would it be possible to return multiple warnings from meteoalarm.org?

**Comment by MrBartusek** [comment]
[MeteoAlarm Integration](https://www.home-assistant.io/integrations/meteoalarm/) returns only one warning. It's a limitation of the integration, not this project. You should request this at [home assistant forums](https://community.home-assistant.io/c/feature-requests/13)
