### ISSUE TITLE
Allow multiline headline

### ISSUE THREAD

**Issue by Tobboss** [MrBartusek/MeteoalarmCard#228]
Using the NINA Integration setting Scaling Mode to Headline and Scale does not give enough information. Just "orange warning" without any details. i have to set scaling_mode to disabled or scale only which truncates the text.

The vertical size of the card is enough to show at least two lines of text. I would love to have the option to switch to multiline. Whether by scaling option, parameter, default or card mod. 
I tried with cardmod to force the multiline parameter but failed because of missing knowledge.

This is my mobile view on mode "scale only". Enough room for more lines. 
![Screenshot_2023-11-03-23-00-18-91_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/MrBartusek/MeteoalarmCard/assets/4268049/c701e36c-ad9a-4f72-8d73-fdf193079b00)

**Comment by MrBartusek** [comment]
Hey! Thank you for your time creating this issue!

Unfortunately, we don't accept any ideas or requests regarding the visual design of the card. As part of our philosophy, we try to keep the design simple, informative and minimal. Any new information bars, icons different display modes are mostly just simply visual clutter. I'll now close this issue, thank you for your contribution!
