### ISSUE TITLE
Error: unknown weather alert types with weatheralert integration

### ISSUE THREAD

**Issue by inguy24** [MrBartusek/MeteoalarmCard#229]
### Describe the bug

It seems it cannot parae alerts with the type 'Beach Hazards' which is an alert type issued by the US NWS in coastal areas. 

### Integration state attributes

alerts:
  - area: San Diego County Coastal Areas; Orange County Coastal
    certainty: Likely
    description: |-
      * WHAT...Areas of lightning at the beaches expected.

      * WHERE...San Diego and Orange County Coastal Areas.

      * WHEN...Until 7 PM PST this evening.

      * IMPACTS...Intra-cloud and cloud-to-ground lightning may occur,
      which may cause serious injury or death.

      * ADDITIONAL DETAILS...The highest chance for lightning will occur
      later this morning into the afternoon, lowering this evening.
    ends: "2023-11-15T19:00:00-08:00"
    event: Beach Hazards Statement
    instruction: Remain out of the water to avoid hazardous swimming conditions.
    response: Avoid
    sent: "2023-11-15T08:57:00-08:00"
    severity: Moderate
    title: >-
      Beach Hazards Statement issued November 15 at 8:57AM PST until November 15
      at 7:00PM PST
    urgency: Expected
    NWSheadline:
      - BEACH HAZARDS STATEMENT IN EFFECT UNTIL 7 PM PST THIS EVENING
    hailSize: "null"
    windGust: "null"
    waterspoutDetection: "null"
    effective: "2023-11-15T08:57:00-08:00"
    expires: "2023-11-15T19:00:00-08:00"
    endsExpires: "2023-11-15T19:00:00-08:00"
    onset: "2023-11-15T09:00:00-08:00"
    status: Actual
    messageType: Alert
    category: Met
    sender: w-nws.webmaster@noaa.gov
    senderName: NWS San Diego CA
    id: urn:oid:2.49.0.1.840.0.4491da39f25f9a0fccc1754a20a989530fdce443.001.1
    zoneid: CAZ552
integration: weatheralerts
state: CA
zone: CAZ552
unit_of_measurement: Alerts
icon: mdi:alert-octagram
friendly_name: Orange County Coastal

### Screenshots

![Screenshot_20231115_091239_Home Assistant](https://github.com/MrBartusek/MeteoalarmCard/assets/37753440/e8daf78b-965e-4ad2-8d89-7dd5bb6bbd40)

### Card version

V2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:layout-card
layout_type: custom:vertical-layout
cards:
  - type: custom:meteoalarm-card
    entities:
      entity: sensor.orange_county_coastal
    integration: weatheralerts
    hide_when_no_warning: true
  - card_config_version: 8
    entity_apparent_temp: sensor.gw2292_feels_like_2
    entity_forecast_icon: weather.kcahunti278
    entity_temperature: sensor.gw2292_temp_2
    section_order:
      - overview

### Integration type

weatheralerts

### Integration configuration

YAML (configuration.yaml)

### Integration Configuration

sensor:
  - platform: weatheralerts
    state: CA
    zone: 552

**Comment by inguy24** [comment]
Any update on this?

**Comment by MrBartusek** [comment]
> Any update on this?

Nope, this is an open source repo and I work on the issues whenever I'm not busy with other things.

**Comment by inguy24** [comment]
I wasn't looking for an immediate fix, just an acknowledgment of the bug report. Since you did list this in HACS, that does mean that users may, in fact, use it. 

⁣Get BlueMail for Android ​

**Comment by MrBartusek** [comment]
Now tracked in: #243
