### ISSUE TITLE
Text in card message

### ISSUE THREAD

**Issue by Repsionu** [MrBartusek/MeteoalarmCard#23]
**Is your feature request related to a problem? Please describe.**
Maybe it is not neccessary to include color text in "messages" as background already has the information on severity so icon+phenomena name are sufficent. 

**Describe the solution you'd like**
Maybe add (optional) event start+end time to entry?
Maybe add an option for message format: only event or event with severity color?

**Additional context**
How is card display related to start and end time- entry is cleared on new RSS message cancelling event?
Best, JR

**Comment by Ryckie** [comment]
I agree with this. I now have a yellow card on my phone saying warning yellow and the actual warning falls off the screen.

**Comment by MrBartusek** [comment]
> Maybe it is not neccessary to include color text in "messages" as background already has the information on severity so icon+phenomena name are sufficient.
> Maybe add an option for message format: only event or event with severity color?

I will work on making a card scale so it would automatically shorten or remove message overall on smaller devices without impacting desktops.

> Maybe add (optional) event start+end time to entry?

Adding any more stuff to the card will make it more cluttered

> How is card display related to start and end time- entry is cleared on new RSS message cancelling event?

The card doesn't do any processing by itself, it displays data directly from the provided entity
