### ISSUE TITLE
Text Scaling

### ISSUE THREAD

**Issue by duczz** [MrBartusek/MeteoalarmCard#232]
### Describe the bug

Headline text is cutting, it it possible to correct these with text scaling?

### Integration state attributes

<html>
<body>

headline: Hochwasserwarnung vor Ausuferungen und Überschwemmungen description: Aufgrund der gefallenen und noch vorhergesagten Niederschläge und der einhergehenden Schneeschmelze kommt es zu einem kräftigen Anstieg der Wasserstände an allen Gewässern im Amtsgebiet. Diese Entwicklung setzt sich bis in die kommende Woche fort.<br/><br/>Isar:<br/>Nach aktueller Vorhersage kann der Pegel Landshut Birket / Isar am Montag Abends die Meldestufe 1 überschreiten. Der Pegel wird dann voraussichtlich mehrere Tage auf diesem Niveau bleiben.<br/><br/>Vils:<br/>Die Pegel Dietelskirchen / Kleine Vils und Vilsbiburg / Große Vils haben am Sonntag Vormittags die Meldestufen 1 überschritten. Die Pegel werden nach aktueller Prognose voraussichtlich weiter auf hohem Niveau bleiben und sich die nächsten Tage im Bereich der Meldestufe 2 bewegen.<br/><br/>Die weitere Entwicklung der Hochwasserlage hängt von den für die nächsten Tage vorhergesagten Niederschlägen in Verbindung mit dem Abschmelzen der Schneedecke ab.<br/>Die Warnung wird bei Vorliegen neuer Erkenntnisse aktualisiert.<br/>Bitte beobachten Sie die tatsächliche Entwicklung der Pegelstände. sender: Wasserwirtschaftsamt Landshut severity: Moderate recommended_actions:  affected_areas: Stadt und Lkr. Landshut id: lhp.LHP.BY.13908_274 sent: 2023-12-10T11:24:00+01:00 start: 2023-12-10T11:21:00+01:00 expires: 2023-12-11T17:00:00+01:00 device_class: safety friendly_name: Warning: xxx 2
--

</body>
</html>

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/25475385/265624c1-3ab1-4b18-a952-cd22b490e70e)

### Card version

v1.1.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
integration: nina
entities:
  - entity: binary_sensor.warning_xxxx_1
override_headline: false
hide_when_no_warning: true
ignored_levels: Yellow
scaling_mode: headline_and_scale

### Integration type

NINA

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
Sorry but it is not possible to put

> Hochwasserwarnung vor Ausuferungen und Überschwemmungen description: Aufgrund der gefallenen und noch vorhergesagten Niederschläge und der einhergehenden Schneeschmelze kommt es zu einem kräftigen Anstieg der Wasserstände an allen Gewässern im Amtsgebiet. Diese Entwicklung setzt sich bis in die kommende Woche fort.

on the card and make it fully visible. You can try using [DWD integration](https://www.home-assistant.io/integrations/dwd_weather_warnings/) it generally has better quality data and just works better with MeteoalarmCard.
