### ISSUE TITLE
Error: Failed to match one of the known prefixes to alert name!

### ISSUE THREAD

**Issue by Khayrisill** [MrBartusek/MeteoalarmCard#237]
### Describe the bug

Environnement Canada issued an advisory but it not correctly reported to the Meteoalarm card.

Not sure if this is coming from environment Canada or something went wrong with the card.

```
Error: Failed to match one of the known prefixes to alert name! Was looking for [ "Avis De" ] and failed (isFrench=true)
name: Meteoalarm
type: custom:meteoalarm-card
integration: env_canada
entities:
  - entity: sensor.chambly_advisory
  - entity: sensor.chambly_statements
  - entity: sensor.chambly_watches
  - entity: sensor.chambly_warnings
scaling_mode: headline_and_scale
hide_when_no_warning: false
disable_swiper: true
```

### Integration state attributes

```

location: Carignan
station: Aéroport de Saint-Hubert
alert_1: Avis Météorologique
alert_time_1: 06 janvier 2024 21h56 HNE
attribution: Données fournies par Environnement Canada
icon: mdi:bell-alert
friendly_name: Chambly Advisory

```

### Screenshots

![Screenshot_2024-01-06-22-47-18-333_io homeassistant companion android-edit](https://github.com/MrBartusek/MeteoalarmCard/assets/93455595/e5805bf1-f50e-461c-a0f1-61b2f32028ad)

### Card version

V2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

name: Meteoalarm
type: custom:meteoalarm-card
integration: env_canada
entities:
  - entity: sensor.chambly_advisory
  - entity: sensor.chambly_statements
  - entity: sensor.chambly_watches
  - entity: sensor.chambly_warnings
scaling_mode: headline_and_scale
hide_when_no_warning: false
disable_swiper: true

### Integration type

Environnement Canada

### Integration configuration

YAML (configuration.yaml)

**Comment by kayrozen** [comment]
I have the same error right now. Seems like this is in lines  190-215 of env_canada.ts

it should have also : 

- Avertissement D'
- Avis D'

like the "Veille D'" on line 202. 

I cannot PR right now but if someone can, i think it would fix it.

`private get entityTypeTranslation(): { en: string[]; fr: string[]; type: EnvCanadaEntityType }[] {
		// English from: https://www.canada.ca/en/environment-climate-change/services/types-weather-forecasts-use/public/criteria-alerts.html
		// French from : https://www.canada.ca/fr/environnement-changement-climatique/services/types-previsions-meteorologiques-utilisation/publiques/criteres-alertes-meteo.html
		return [
			{
				type: EnvCanadaEntityType.Warning,
				en: ['Warning'],
				fr: ['Avertissement De'],
			},
			{
				type: EnvCanadaEntityType.Watch,
				en: ['Watch'],
				fr: ['Veille De', "Veille D'"],
			},
			{
				type: EnvCanadaEntityType.Statement,
				en: ['Statement'],
				fr: ['Bulletin'],
			},
			{
				type: EnvCanadaEntityType.Advisory,
				en: ['Advisory'],
				fr: ['Avis De'],
			},
		];
	}
`

**Comment by MrBartusek** [comment]
Hey, can you guys help me understand this? Is `Avis Météorologique` like a general not-specific alert?

If that's the cause we would also need to map `Météorologique` to a unknown alert

**Comment by kayrozen** [comment]
> Hey, can you guys help me understand this? Is `Avis Météorologique` like a general not-specific alert?
> 
> If that's the cause we would also need to map `Météorologique` to a unknown alert

yes it is

**Comment by MrBartusek** [comment]
Thank you guys :heart: This will be a part of `v2.7.0`
