### ISSUE TITLE
option to not include warning colour in headline

### ISSUE THREAD

**Issue by b3ntcanadian** [MrBartusek/MeteoalarmCard#246]
Can an option be added to suppress stating the colour as part of the headline text. For example, the text on a red card would be "snow/ice warning" rather than "Red snow/ice warning". 

This would be make the card easier to read and look cleaner on smaller screens.

**Comment by MrBartusek** [comment]
> This would be make the card easier to read and look cleaner on smaller screens.

This is already implemented. The card will only show the warning name on smaller screen sizes. Other than that it's a minor issue that would require another customisation options. We won't be adding this, it's not worth it.
