### ISSUE TITLE
meteo-france integration is unavailable

### ISSUE THREAD

**Issue by merlin-marvin** [MrBartusek/MeteoalarmCard#249]
### Describe the bug

Hello,

Meteo-france intégration display "integration is unavailable"

No entities available except "update.meteoalarm_card_update"

Thanks

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/58307037/48b45b2b-2042-4f44-992d-66c87d9c3eb1)

### Card version

2.5.4

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

type: custom:meteoalarm-card
entities:
  - entity: update.meteoalarm_card_update
integration: meteofrance

### Integration type

Météo-France

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
You need to setup [Meteo-France](https://www.home-assistant.io/integrations/meteo_france/) integration before using this card.

**Comment by merlin-marvin** [comment]
so now I feel a bit ashamed.
Sorry, I'm new to Home Assistant.

Thanks for the help !
