### ISSUE TITLE
Orange Background Color

### ISSUE THREAD

**Issue by Maddin1684** [MrBartusek/MeteoalarmCard#253]
### Describe the bug

Hello 👋 

If there was a Level2 DWD-Warning (orange) it is displayed at `—red-Level-color`

Is it possible to show Level2 Warnings it in „orange-level-background-color“?

### Integration state attributes

.

### Screenshots

Orange warning is shown in red color (LVL2)

### Card version

act 

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

.

### Integration type

Meteoalarm

### Integration configuration

YAML (configuration.yaml)

**Comment by MrBartusek** [comment]
You have not filed the template nor provided the required information to troubleshoot your problem. Please create a new issue and include all required context.
