### ISSUE TITLE
Add DWD detailed description but translated to other languages

### ISSUE THREAD

**Issue by FS1961** [MrBartusek/MeteoalarmCard#254]
**Is your feature request related to a problem? Please describe.**
1st - your card is great! Thanks for the effort.

Would love it if you could add the DWD warning complete descriptions to the card but translated. This would be an enhancement not a bug issue. I am using a card that someone suggested and I get the complete detail but it's only in German. Please see pic below

**Describe the solution you'd like**
Display the complete detailed warning descriptions below the "warning level" in the card with the option to translate to English or other languages.

**Additional context**
<img width="1493" alt="Screenshot 2024-05-17 at 10 55 09 AM" src="https://github.com/MrBartusek/MeteoalarmCard/assets/98458806/75b8c47a-ac38-406d-a686-1d6c06e77785">

**Comment by MrBartusek** [comment]
The code that you've sent is not in any way related to MeteoalarmCard. We do not display the description of the warnings - translated nor un-translated.

**Comment by FS1961** [comment]
Okay, no problem. 

Thanks for your effort.
