### ISSUE TITLE
Color not fitting warning level

### ISSUE THREAD

**Issue by Laho812** [MrBartusek/MeteoalarmCard#255]
### Describe the bug

Hello,
i'm using 2x cards in one view, on the right only the entity for current weather warning (level 2 = orange) and on the left 1x only the entity for advance weather warning (level 3 = red). But both cards are colored red.
In my opinion the left card should be colored orange and the right should be colored red, as it is.

### Integration state attributes

**Advance Warning level**
region_name: Main-Kinzig-Kreis
region_id: 106435000
last_update: 2024-05-21T11:44:59.248000+00:00
warning_count: 1
warning_1_name: VORABINFORMATION SCHWERES GEWITTER
warning_1_type: 40
warning_1_level: 3
warning_1_headline: VORABINFORMATION UNWETTER vor SCHWEREM GEWITTER
warning_1_description: Ab dem frühen Dienstagnachmittag und bis in die Nacht zum Mittwoch hinein sind schwere Gewitter möglich, die im Verlauf gebietsweise auch zu einem größeren Niederschlagskomplex zusammenwachsen können. Dabei sind kleinkörniger Hagel und Sturmböen um 75 km/h (8 bis 9 Bft) möglich. Die Hauptgefahr besteht jedoch durch lokal heftigen Starkregen mit Mengen bis 40 l/qm in kurzer Zeit, vereinzelt auch darüber. Innerhalb weniger Stunden können kleinräumig zwischen 40 und 60 l/qm, vereinzelt bis 80 l/qm zusammenkommen.

Es besteht die Gefahr von Überschwemmungen, Erdrutschen sowie vollgelaufenen Kellern und Unterführungen. Allgemein besteht bei Gewittern die Gefahr von Blitzschlag.
warning_1_instruction: Dies ist ein Hinweis auf eine Wetterlage mit hohem Unwetterpotenzial. Er soll die rechtzeitige Vorbereitung von Schutzmaßnahmen ermöglichen.

Hilfestellung unter: www.dwd.de/handlungsempfehlungen/vorabinformation

Gewitter mit den genannten Begleiterscheinungen treten typischerweise sehr lokal auf und treffen mit voller Intensität meist nur wenige Orte. Genauere Angaben zu Ort, Gebiet und Zeitpunkt des Ereignisses können erst mit der Ausgabe der amtlichen Warnungen erfolgen. Bitte verfolgen Sie die weiteren Wettervorhersagen mit besonderer Aufmerksamkeit.
warning_1_start: 2024-05-21T12:00:00+00:00
warning_1_end: 2024-05-22T00:00:00+00:00
warning_1_parameters: null
warning_1_color: #ff8080
warning_1: 
start_time: '2024-05-21T12:00:00+00:00'
end_time: '2024-05-22T00:00:00+00:00'
event: VORABINFORMATION SCHWERES GEWITTER
event_code: 40
headline: VORABINFORMATION UNWETTER vor SCHWEREM GEWITTER
description: >-
  Ab dem frühen Dienstagnachmittag und bis in die Nacht zum Mittwoch hinein sind
  schwere Gewitter möglich, die im Verlauf gebietsweise auch zu einem größeren
  Niederschlagskomplex zusammenwachsen können. Dabei sind kleinkörniger Hagel
  und Sturmböen um 75 km/h (8 bis 9 Bft) möglich. Die Hauptgefahr besteht jedoch
  durch lokal heftigen Starkregen mit Mengen bis 40 l/qm in kurzer Zeit,
  vereinzelt auch darüber. Innerhalb weniger Stunden können kleinräumig zwischen
  40 und 60 l/qm, vereinzelt bis 80 l/qm zusammenkommen.

  Es besteht die Gefahr von Überschwemmungen, Erdrutschen sowie vollgelaufenen
  Kellern und Unterführungen. Allgemein besteht bei Gewittern die Gefahr von
  Blitzschlag.
instruction: >-
  Dies ist ein Hinweis auf eine Wetterlage mit hohem Unwetterpotenzial. Er soll
  die rechtzeitige Vorbereitung von Schutzmaßnahmen ermöglichen.

  Hilfestellung unter: www.dwd.de/handlungsempfehlungen/vorabinformation

  Gewitter mit den genannten Begleiterscheinungen treten typischerweise sehr
  lokal auf und treffen mit voller Intensität meist nur wenige Orte. Genauere
  Angaben zu Ort, Gebiet und Zeitpunkt des Ereignisses können erst mit der
  Ausgabe der amtlichen Warnungen erfolgen. Bitte verfolgen Sie die weiteren
  Wettervorhersagen mit besonderer Aufmerksamkeit.
urgency: future
level: 3
parameters: null
color: '#ff8080'

attribution: Data provided by DWD
friendly_name: DWD Weather Warnings Main-Kinzig-Kreis Vorwarnstufe

**Current warning level**
region_name: Main-Kinzig-Kreis
region_id: 106435000
last_update: 2024-05-21T11:44:59.248000+00:00
warning_count: 1
warning_1_name: STARKES GEWITTER
warning_1_type: 36
warning_1_level: 2
warning_1_headline: Amtliche WARNUNG vor STARKEM GEWITTER
warning_1_description: Es treten Gewitter auf. Dabei gibt es Sturmböen mit Geschwindigkeiten bis 65 km/h (18 m/s, 35 kn, Bft 8) sowie Starkregen mit Niederschlagsmengen zwischen 15 l/m² und 25 l/m² pro Stunde.
warning_1_instruction: Gefahr durch 
 · Blitzschlag (Lebensgefahr!)
 · einzelne herabstürzende Äste
 · umherfliegende Gegenstände
 · vereinzelte, rasche Überflutungen von Straßen/Unterführungen
 · Aquaplaning

Handlungsempfehlungen: 
 · Aufenthalt im Freien vermeiden oder Schutz suchen (z.B. in Gebäuden)
 · Gewässer meiden
 · frei stehende Objekte sichern (z.B. Leinwände und Möbel)
 · z.B. Zelte und Abdeckungen befestigen
 · im Freien auf herabfallende Gegenstände (z.B. Äste) achten
 · Verhalten im Straßenverkehr anpassen
 · überflutete und gefährdete Abschnitte (wie Unterführungen) meiden
warning_1_start: 2024-05-21T11:21:00+00:00
warning_1_end: 2024-05-21T12:30:00+00:00
warning_1_parameters: 
Böen: <65 [km/h]
Niederschlag: 15-25 [l/m² in 1h]

warning_1_color: #fb8c00
warning_1: 
start_time: '2024-05-21T11:21:00+00:00'
end_time: '2024-05-21T12:30:00+00:00'
event: STARKES GEWITTER
event_code: 36
headline: Amtliche WARNUNG vor STARKEM GEWITTER
description: >-
  Es treten Gewitter auf. Dabei gibt es Sturmböen mit Geschwindigkeiten bis 65
  km/h (18 m/s, 35 kn, Bft 8) sowie Starkregen mit Niederschlagsmengen zwischen
  15 l/m² und 25 l/m² pro Stunde.
instruction: "Gefahr durch \n\_·\_Blitzschlag (Lebensgefahr!)\n\_·\_einzelne herabstürzende Äste\n\_·\_umherfliegende Gegenstände\n\_·\_vereinzelte, rasche Überflutungen von Straßen/Unterführungen\n\_·\_Aquaplaning\n\nHandlungsempfehlungen: \n\_·\_Aufenthalt im Freien vermeiden oder Schutz suchen (z.B. in Gebäuden)\n\_·\_Gewässer meiden\n\_·\_frei stehende Objekte sichern (z.B. Leinwände und Möbel)\n\_·\_z.B. Zelte und Abdeckungen befestigen\n\_·\_im Freien auf herabfallende Gegenstände (z.B. Äste) achten\n\_·\_Verhalten im Straßenverkehr anpassen\n\_·\_überflutete und gefährdete Abschnitte (wie Unterführungen) meiden"
urgency: immediate
level: 2
parameters:
  Böen: <65 [km/h]
  Niederschlag: 15-25 [l/m² in 1h]
color: '#fb8c00'

attribution: Data provided by DWD
friendly_name: DWD Weather Warnings Main-Kinzig-Kreis Aktuelle Warnstufe

### Screenshots

![grafik](https://github.com/MrBartusek/MeteoalarmCard/assets/119891233/0f243865-141e-4f6b-8e5e-bd078961104b)
- Left: Only the entity for current weather warning (level 2 = orange)
- Right: Only the entity for advance weather warning (level 3 = red)

### Card version

v2.7.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

**Left: Only the entity for current weather warning (level 2 = orange)**
```yaml
type: custom:meteoalarm-card
integration: dwd
entities:
` - entity: sensor.dwd_weather_warnings_main-kinzig-kreis_current_warning_level
override_headline: false
hide_when_no_warning: true
disable_swiper: false
hide_caption: false
scaling_mode: headline
```

**Right: Only the entity for advance weather warning (level 3 = red)**
```yaml
type: custom:meteoalarm-card
integration: dwd
entities:
  - entity: sensor.dwd_weather_warnings_main-kinzig-kreis_advance_warning_level
override_headline: false
hide_when_no_warning: false
disable_swiper: false
hide_caption: false
scaling_mode: headline
```

### Integration type

Deutscher Wetterdienst (DWD)

### Integration configuration

GUI

**Comment by MrBartusek** [comment]
It seams to be an issue affecting every integraiton - orange warnings are shown as red
