### ISSUE TITLE
2 alerts, only one displayed

### ISSUE THREAD

**Issue by Repsionu** [MrBartusek/MeteoalarmCard#27]
I guess that I misundestood or configured something wrong but I always get only one warning using meteoalarmeu integration:
![Alarm_meteo_problem](https://user-images.githubusercontent.com/46962963/119535219-7329ed80-bd90-11eb-9d50-ca8ca9980b88.png)
What can be wrong on my side?
Best, JR

**Comment by MrBartusek** [comment]
Hey, the way the card is constructed just doesn't allow for displaying more than one alert at a time. It just isn't designed to display more information.
