### ISSUE TITLE
Met Office new integration request

### ISSUE THREAD

**Issue by nightmare1111** [MrBartusek/MeteoalarmCard#275]
the met office is used u=in the UK for weather forcasts and has a rss feed
https://www.metoffice.gov.uk/weather/guides/rss
typical attributes example

entries: 
- title: Yellow warning of wind affecting Northern Ireland
  title_detail:
    type: text/plain
    language: null
    base: https://www.metoffice.gov.uk/public/data/PWSCache/WarningsRSS/Region/ni
    value: Yellow warning of wind affecting Northern Ireland
  links:
    - rel: alternate
      type: text/html
      href: >-
        https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings#?date=2024-12-17&id=7441c9ff-7ca5-4490-8a5b-9349d9377042&referrer=rss
    - length: '15776'
      type: image/png
      href: >-
        https://data.consumer-digital.api.metoffice.gov.uk/v1/warnings/rss/image/yellow-wind.png
      rel: enclosure
  link: >-
    https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings#?date=2024-12-17&id=7441c9ff-7ca5-4490-8a5b-9349d9377042&referrer=rss
  summary: >-
    Yellow warning of wind affecting Northern Ireland: County Antrim, County
    Down valid from 1500 Tue 17 Dec to 0800 Wed 18 Dec
  summary_detail:
    type: text/html
    language: null
    base: https://www.metoffice.gov.uk/public/data/PWSCache/WarningsRSS/Region/ni
    value: >-
      Yellow warning of wind affecting Northern Ireland: County Antrim, County
      Down valid from 1500 Tue 17 Dec to 0800 Wed 18 Dec
  id: >-
    https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings#?date=2024-12-17&id=7441c9ff-7ca5-4490-8a5b-9349d9377042&referrer=rss&region=Northern
    Ireland
  guidislink: false

icon: mdi:rss
friendly_name: Northern Ireland Weather Warning

**Comment by MrBartusek** [comment]
duplicate: https://github.com/MrBartusek/MeteoalarmCard/issues/272

**Comment by MrBartusek** [comment]
> I had only added it as you documentation had suggested to send suggestions.🤣

Hey! Our [contributing guide](https://github.com/MrBartusek/MeteoalarmCard/blob/master/CONTRIBUTING.md#how-to-report-bugs-and-propose-new-features) suggest searching existing issues before opening new one, maybe you have overlooked it
