### ISSUE TITLE
Meteoalarm.eu migrates to https://meteoalarm.org

### ISSUE THREAD

**Issue by TheLordVader** [MrBartusek/MeteoalarmCard#34]
Meteoalarm has moved to https://meteoalarm.org –The old system (meteoalarm.eu) will retire on 31 May 2021. 

Warnings from Sweden dosen't work with old site anymore.

See banner at startpage on Meteoalarm.eu

Best regards 
Anders

**Comment by MrBartusek** [comment]
Hey, this card does not provide any data by itself. It only displays data provided by the integration. Please report this issue to [xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu) or [Home Assistant](https://github.com/home-assistant/core/issues).
