### ISSUE TITLE
Gt.find is not a function

### ISSUE THREAD

**Issue by gume** [MrBartusek/MeteoalarmCard#35]
**Describe the bug**
My HA cannot display the card. It is a red box, and on the top it says "Gt.find is not a function"

**To Reproduce**
I just installed the card with HACS. I never had a running version with this card before.

**System (please complete the following information):**
 - Card version: 1.7.0
 - Integration type: I tried several: meteoalarm, Meteo France, meteoalarmeu
 - Installation type: HACS

**Comment by MrBartusek** [comment]
Hey, could you send a screenshot of the error card (that red box) and the error from your browser console?

**Comment by gume** [comment]
![image](https://user-images.githubusercontent.com/4092829/120385370-9d972000-c327-11eb-847f-008c1efc09cd.png)
![image](https://user-images.githubusercontent.com/4092829/120385444-bb648500-c327-11eb-9648-98d2b91925ea.png)

**Comment by gume** [comment]
I mistyped the sensor to "meteoatarm", but it is the sensor name in my config. I have data on that name. I will correct it, but I do not think that it would be a problem.

**Comment by MrBartusek** [comment]
Yes, I can confirm that issue is happening and it will be fixed as soon as possible. The temporary fix is to keep integration on `automatic` or downgrade card to version `v1.6.0`

**Comment by MrBartusek** [comment]
Fixed in `v1.7.1` 🎉
