### ISSUE TITLE
DWD integration?

### ISSUE THREAD

**Issue by RubenKelevra** [MrBartusek/MeteoalarmCard#37]
Hey guys,

I was wondering if there's a chance to support the DWD integration to get Official Warning for Germany? :)

https://www.home-assistant.io/integrations/dwd_weather_warnings/

**Comment by MrBartusek** [comment]
Hey, thanks for the idea! Support for DWD will be added in the next update after this is resolved: https://github.com/home-assistant/core/issues/51502

**Comment by MrBartusek** [comment]
Added in https://github.com/MrBartusek/MeteoalarmCard/commit/baf667ce8056408343a44e6987d3fd85a1ce85e3
