### ISSUE TITLE
xlcnd/meteoalarmeu is now deprecated

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/MeteoalarmCard#38]
![image](https://user-images.githubusercontent.com/23432278/124773153-f7998f80-df3c-11eb-94cd-f9891b49e6a4.png)

One of the integrations supported by card [xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu) has been deprecated due to the changes in meteoalarm API by the library owner. The card will show a warning when using that integration and **soon it will be removed from the project entirely**. 
See xlcnd/meteoalarmeu#23

As of home assistant version [2021.7.0](https://www.home-assistant.io/blog/2021/07/07/release-20217/) - [meteoalarm](https://www.home-assistant.io/integrations/meteoalarm/) integration is available to all participating countries so you can switch to using core integration.

**Comment by Yersi88** [comment]
Hi, I tried to migrate to core integration meteolaram but it doesn't work. 

I use this in my config.yaml: 

binary_sensor:
  - platform: meteoalarm
    name: Meteoalarm London
    country: 'UK'
    province: 'London-South-East'

it never creates the entity. Any idea how to make it work?

**Comment by MrBartusek** [comment]
@Yersi88 See #43
