### ISSUE TITLE
Only one warning shown

### ISSUE THREAD

**Issue by sgofferj** [MrBartusek/MeteoalarmCard#39]
**Describe the bug**
The card only shows one warning, even when more are active.

**To Reproduce**
1. Configure the card for a sensor
2. Wait for multiple active warnings

**Expected behavior**
The card should show all active warnings, ideally in order of severity, most severe first.

**Screenshots**
![Screenshot_20210607_132023](https://user-images.githubusercontent.com/3258466/121000702-2fbd7f00-c793-11eb-8fc2-3643f60e716d.png)
![Screenshot_20210607_131716](https://user-images.githubusercontent.com/3258466/121000326-c0478f80-c792-11eb-8ee1-097e43429138.png)

**System (please complete the following information):**
 - Card version: 1.7.2
 - Integration type: xlcnd
 - Installation type: HACS

**Comment by MrBartusek** [comment]
Duplicate #27
