### ISSUE TITLE
Add support for xlcnd/meteoalarmeu

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/MeteoalarmCard#4]
[xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu) is custom component, an alternative to core integration. It shares very similar functionality to the core one so it would be great to support it!

**Comment by nurtext** [comment]
I would like to see this integration as well, because the official meteoalarm.eu integration from HA doesn't seem to work anymore. For reference see: https://github.com/home-assistant/core/issues/45063

**Comment by nurtext** [comment]
Thanks for integrating xlcnd/meteoalarmeu! Seems a new release is missing? 1.4.0 only contains newly added translations. Would you mind creating the 1.4.1 release for us? Cheers!

**Comment by MrBartusek** [comment]
@nurtext No problem, I will release a new version today
