### ISSUE TITLE
Multiline

### ISSUE THREAD

**Issue by ajtudela** [MrBartusek/MeteoalarmCard#42]
**Is your feature request related to a problem? Please describe.**
Unable to read.

**Describe the solution you'd like**
Multiline text.

**Additional context**
Hi, I don't know if is possible but it would be nicer if you add multiline text. In spanish is difficult to read. Thanks!
![Captura](https://user-images.githubusercontent.com/4681902/123542538-6c551880-d74a-11eb-8fb2-8f3210d32378.PNG)

**Comment by MrBartusek** [comment]
Hey, I'm not too much into adding multiline text to the card. This will ruin its minimalistic look and it's not this card design goal. I will keep this issue open as of now because I have some ideas that *may* resolve this issue and similar ones. If you want to fix it temporarily you can try enabling the `override_headline` option.

**Comment by ajtudela** [comment]
Great!. I'll keep and eye

**Comment by fabir-git** [comment]
Would some kind of auto-scrolling text be possible?

**Comment by MrBartusek** [comment]
> Would some kind of auto-scrolling text or auto adjust to the text size be possible?
> I have the same problem with the text on mobile devices, it gets cut off (even with the override_headline).

This may be a bug actually, text shouldn't be cut when using `override_headline` can you send a screenshot?

**Comment by fabir-git** [comment]
![Screenshot_20210724-222732~2](https://user-images.githubusercontent.com/62546027/126902770-5617daf1-332c-4685-9953-0e0283af9838.png)
This was a screenshot of the text.

**Comment by ravexx** [comment]
I managed it so:
```
style: |
  .status, .status-narrow, .status-both {
    overflow: inherit;
    overflow-wrap: break-word;
    display: inline;
  }
```

**Comment by MrBartusek** [comment]
I just pushed commit for dynamically scaling card. This enhances the code added in https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v1.7.0 to use actually the width of the headline rather than just pre-set screen sizes. This will be available in the next release!
