### ISSUE TITLE
Error: This integration doesn't support provided entity!

### ISSUE THREAD

**Issue by gartenbauer** [MrBartusek/MeteoalarmCard#44]
**Describe the bug**
I get the fallowing error when adding the card to my lovelace dashboard: 
```
Error: This integration doesn't support provided entity!
type: custom:meteoalarm-card
entity: binary_sensor.meteoalarm
integration: meteoalarm
override_headline: false
```

**To Reproduce**
1. Choose the lovelace dashboard
2. clock on: +add card
3. add the meteoalarm-card
4. chose the entity: binary_sensor.meteoalarm

**Attributes of the entity: binary_sensor.meteoalarm**
```
language: en-GB
category: Met
event: Yellow Rain Warning
responseType: None
urgency: Expected
severity: Moderate
certainty: Likely
effective: 2021-07-15T00:00:00+02:00
onset: 2021-07-15T00:00:00+02:00
expires: 2021-07-16T21:00:00+02:00
senderName: MeteoSwiss
headline: Yellow Rain Warning for Switzerland - Wohlen-Albis
description: - Expected amounts: 40-60 mm
- Snowfall limit: 2700-3000 m
web: http://www.meteoswiss.admin.ch
contact: meteoalarm.cap@meteoswiss.ch
attribution: Information provided by MeteoAlarm
friendly_name: meteoalarm
device_class: safety
```

**Screenshot**
![image](https://user-images.githubusercontent.com/49751694/125687396-3c369d61-7064-46c7-8dcc-d3f5450aa22d.png)

**System:**
 - Card version: v1.9.0
 - Integration type: Core
 - Installation type: HACS

**Comment by MrBartusek** [comment]
Hey, it seams like you are trying to use [custom xlcnd/meteoalarmeu](https://github.com/xlcnd/meteoalarmeu) while selecting `integration: meteoalarm` which is a mode for [core integration](https://www.home-assistant.io/integrations/meteoalarm/) and that's the issue.

The next this is **you shouldn't use xlcnd integration anymore** see: #38

**Comment by gartenbauer** [comment]
Thanks for your response, but I did not install the custom integration. To be honest I have no clue from which source HA has the attributes of the binary sensor. Because on meteoalarm.org are no alerts listed for my region. 🤨
Seems like I need to investigate this by myself. Thank you nevertheless for making this nice custom card.

**Comment by DarkWarden85** [comment]
Hi! I am having the same issue. I use the core meteoalarm integration but get the same error than @gartenbauer. I also don't use the deprecated custom integration. Is there any way to get rid of this error?

**Comment by MrBartusek** [comment]
> Hi! I am having the same issue. I use the core meteoalarm integration but get the same error than @gartenbauer. I also don't use the deprecated custom integration. Is there any way to get rid of this error?

Hey, please [create new issue](https://github.com/MrBartusek/MeteoalarmCard/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and attach screenshots, configuration and console logs
