### ISSUE TITLE
Card breaks when `Awareness level` and `Awareness type` are not provided

### ISSUE THREAD

**Issue by DarkWarden85** [MrBartusek/MeteoalarmCard#48]
**Describe the bug**
I have been using the MeteoalarmCard in conjunction with the core meteoalarm integration for a few weeks without any issues. However, it has stopped working a few days ago because it supposedly doesn't support the same provided binary_sensor.meteoalarm entity anymore which worked fine until recently.

**To Reproduce**
- Add MeteoalarmCard to a Lovelace dashboard
- Click on edit
- Select entity binary_sensor.meteoalarm

**Screenshots**
![image](https://user-images.githubusercontent.com/79642261/126877209-a5d76846-d104-4fcd-a105-54977262a16d.png)

**System (please complete the following information):**
- Card version: v1.9.0
- Integration type: Core
- Installation type: HACS

**Comment by MrBartusek** [comment]
Hey, please attach logs from your console

**Comment by DarkWarden85** [comment]
I'm not entirely sure what you mean with logs as I cannot find any entries in my home assistant log or any log entry in dev tools. Sorry, I'm a noob in this regard :(. Could you please provide more detailed instructions?

**Comment by MrBartusek** [comment]
@DarkWarden85  You can access your browser console by pressing F12, it may be different depending on your browser, if that doesn't work just google `<your browser> developer console`.

Then i will need a screenshot of attributes of `binary_sensor.meteoalarm` sensor from your HA dev tools:

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by DarkWarden85** [comment]
Thanks @MrBartusek for clarification.

Logs:

`app.62541dd1.js:13499 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.62541dd1.js:13499
:8123/local/scheduler-card/dist/scheduler-card.js?v=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
simple-thermostat.js:285 simple-thermostat: 2.4.2
vertical-stack-in-card.js:1 vertical-stack-in-cardVersion: 0.4.1
layout-card.js?hacstag=156434866230:223 LAYOUT-CARD 2.3.0 IS INSTALLED 
slider-entity-row.js:59 SLIDER-ENTITY-ROW 17.1.0 IS INSTALLED 
banner-card.js:162 banner-card: 0.12.0
paper-buttons-row.js?hacstag=244872232060:1  PAPER-BUTTONS-ROW  0.6.0 
fold-entity-row.js:42 FOLD-ENTITY-ROW 20.0.4 IS INSTALLED 
decluttering-card.js:831  DECLUTTERING-CARD    Version 0.6.3   
chunk.59536e6ae6caec2cfd80.js:1 Uncaught (in promise) http://homeassistant.local:8123/local/scheduler-card/dist/scheduler-card.js?v=0
multiple-entity-row.js:1  MULTIPLE-ENTITY-ROW  4.2.0 
card-tools.js:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 2902d886-22cbeb65
auto-entities.js:210 AUTO-ENTITIES 1.9.1 IS INSTALLED 
button-card.js:425   BUTTON-CARD   Version 3.4.2 
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.10.0 
meteoalarm-card.js?hacstag=361205663190:339 === METEOALARM CARD ERROR ===
Report issue: https://bit.ly/3hK1hL4 

 Error: This integration doesn't support provided entity!
    at HTMLElement.getAttributes (meteoalarm-card.js?hacstag=361205663190:289)
    at HTMLElement.render (meteoalarm-card.js?hacstag=361205663190:325)
    at HTMLElement.update (meteoalarm-card.js?hacstag=361205663190:159)
    at HTMLElement.performUpdate (meteoalarm-card.js?hacstag=361205663190:134)
    at HTMLElement._enqueueUpdate (meteoalarm-card.js?hacstag=361205663190:134)
render @ meteoalarm-card.js?hacstag=361205663190:339
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
meteoalarm-card.js?hacstag=361205663190:339 === METEOALARM CARD ERROR ===
Report issue: https://bit.ly/3hK1hL4 

 Error: This integration doesn't support provided entity!
    at HTMLElement.getAttributes (meteoalarm-card.js?hacstag=361205663190:289)
    at HTMLElement.render (meteoalarm-card.js?hacstag=361205663190:325)
    at HTMLElement.update (meteoalarm-card.js?hacstag=361205663190:159)
    at HTMLElement.performUpdate (meteoalarm-card.js?hacstag=361205663190:134)
    at HTMLElement._enqueueUpdate (meteoalarm-card.js?hacstag=361205663190:134)
render @ meteoalarm-card.js?hacstag=361205663190:339
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
secondaryinfo-entity-row.js:38 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)
meteoalarm-card.js?hacstag=361205663190:339 === METEOALARM CARD ERROR ===
Report issue: https://bit.ly/3hK1hL4 

 Error: This integration doesn't support provided entity!
    at HTMLElement.getAttributes (meteoalarm-card.js?hacstag=361205663190:289)
    at HTMLElement.render (meteoalarm-card.js?hacstag=361205663190:325)
    at HTMLElement.update (meteoalarm-card.js?hacstag=361205663190:159)
    at HTMLElement.performUpdate (meteoalarm-card.js?hacstag=361205663190:134)
    at HTMLElement._enqueueUpdate (meteoalarm-card.js?hacstag=361205663190:134)
render @ meteoalarm-card.js?hacstag=361205663190:339
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
fold-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement.applyStyle (fold-entity-row.js:1)
`

Attributes of binary_sensor.meteoalarm:
![image](https://user-images.githubusercontent.com/79642261/126896781-2590d9fb-8739-4137-9c53-26b34be261b8.png)

**Comment by MrBartusek** [comment]
Seams odd, could you provide your sensor configuration from `configuration yaml` ?

**Comment by DarkWarden85** [comment]
Yes, sure:

![image](https://user-images.githubusercontent.com/79642261/126898676-d7dc5599-9d1b-4052-a70d-2dfbf3bdd944.png)

**Comment by AndyVRD** [comment]
Just wanted to change my language but it was not working, deleted the language part in my sensor configuration and now have the same problem. Was working fine before i changed the language and restarted HA...

**Comment by DarkWarden85** [comment]
I noticed another detail of this bug. A few days ago, the meteoalarm started working normally again all by itself. I couldn't really figure out why at that time. Later I got the answer when a new weather alarm was issued: The error immediately turned up again. It seems that the card works fine when the binary_sensor.meteoalarm is in the off state. As soon as it enters on state, the card displays the error message discussed in this thread.

**Comment by kalhimeo** [comment]
Hi, I have the same error here, started only a few days ago :

```
meteoalarm-card.js?hacstag=361205663190:339 === METEOALARM CARD ERROR ===
Report issue: https://bit.ly/3hK1hL4 

 Error: This integration doesn't support provided entity!
    at HTMLElement.getAttributes (:8123/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663190:289)
    at HTMLElement.render (:8123/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663190:325)
    at HTMLElement.update (:8123/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663190:159)
    at HTMLElement.performUpdate (:8123/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663190:134)
    at HTMLElement._enqueueUpdate (:8123/hacsfiles/MeteoalarmCard/meteoalarm-card.js?hacstag=361205663190:134)
render @ meteoalarm-card.js?hacstag=361205663190:339
```

binary_sensor data :
```
language: fr-BE
category: Met
event: Avertissement verte orage
responseType: None
urgency: Expected
severity: Moderate
certainty: Likely
effective: '2021-05-11T18:00:00+02:00'
onset: '2021-05-11T18:00:00+02:00'
expires: '2021-08-01T21:00:00+02:00'
senderName: Institut Royal Météorologique de Belgique
headline: Avertissement verte orage en Belgique - Brabant
description: Aucune attention particulière nécessaire
web: https://www.meteo.be/fr/meteo/avertissements/carte-de-belgique
awareness_level: 1; Green; Minor
awareness_type: 3; Thunderstorm
attribution: Information provided by MeteoAlarm
friendly_name: meteoalarm
device_class: safety
```

Note that for the same HA dashboard I have this error on Edge and Chrome, but not in the Android mobile app.

Hope this helps and thanks for the great integration !

**Comment by viktak** [comment]
Same error for me too for the last few days.

Thanks for the UI!!

**Comment by MrBartusek** [comment]
@DarkWarden85 sorry for the delayed response! It seems like in very rare scenarios `Awareness level` and `Awareness type` are not present, i will investigate it a bit more and include fix for these scenarios in next relese

> Just wanted to change my language but it was not working, deleted the language part in my sensor configuration and now have the same problem. Was working fine before i changed the language and restarted HA...
> 
> Btw, my binary_sensor.meteoalarm is working fine so that's not the issue.

If you think that this issue is different that this one, please [create an issue](https://github.com/MrBartusek/MeteoalarmCard/issues/new/choose)

> I noticed another detail of this bug. A few days ago, the meteoalarm card started working normally again all by itself. I couldn't really figure out why at that time. Later I got the answer when a new weather alarm was issued: The error immediately turned up again. It seems that the card works fine when the binary_sensor.meteoalarm is in state 'off'. As soon as it enters 'on' state, the card displays the error message discussed in this thread.

This is expected since this error is alert parsing issue so your card will function normally when there are no warnings

@kalhimeo I just set up my integration for France and it works without any problem, please try to update your HA and reinstall card, if the issue persist [create an issue](https://github.com/MrBartusek/MeteoalarmCard/issues/new/choose)

**Comment by kalhimeo** [comment]
Hi MrBartusek,
Thanks for the update. I did not update to HA 2021.08 yet so I will do that in the following days and try again, but for info I am not using the integration for France but for Belgium in french language.
Best regards, Laurent

**Comment by MrBartusek** [comment]
@kalhimeo Okay then, I didn't notice that! I will wait for any Belgium alerts to come up and I will check that.

**Comment by kalhimeo** [comment]
thank you !

**Comment by DeviantUK** [comment]
@MrBartusek, parts of the UK have a warning today.
```
binary_sensor:
  - platform: meteoalarm
    country: 'united-kingdom'
    province: 'South West England'
```

Entity `binary_sensor.meteoalarm`:
```
language: en-GB
category: Met
event: Yellow thunderstorm warning
responseType: Prepare
urgency: Future
severity: Moderate
certainty: Possible
effective: '2021-08-09T09:36:11+00:00'
onset: '2021-08-09T11:00:00+00:00'
expires: '2021-08-09T20:00:00+00:00'
senderName: UK Met Office
headline: >-
  While many places will stay dry, heavy showers and thunderstorms may cause
  flooding and travel disruption in a few places.
description: >-
  Heavy, slow-moving, thundery downpours will develop today. Some places will
  miss these, but where they do occur, 10-20 mm rain may fall in a short space
  of time, perhaps with 20-40mm over 2 or 3 hours in a few places. The showers
  will die out during the evening. For further details see
  https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings
instruction: >-
  What to expect: There is a small chance that homes and businesses could be
  flooded quickly, with damage to some buildings from floodwater, lightning
  strikes, hail or strong winds; Spray and sudden flooding could lead to
  difficult driving conditions and some road closures; There is a small chance
  that some communities become cut off by flooded roads; Where flooding or
  lightning strikes occur, there is a chance of delays and some cancellations to
  train and bus services; There is a slight chance that power cuts could occur
  and other services to some homes and businesses could be lost.
web: https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings
attribution: Information provided by MeteoAlarm
friendly_name: meteoalarm
device_class: safety
```
![image](https://user-images.githubusercontent.com/16081842/128709741-8106971f-71a9-4b1a-bd3e-5560c6f99320.png)

**Comment by MrBartusek** [comment]
@DeviantUK yes, it seems that UK don't send `Awareness level` and `Awareness type`  too, it will be fixed in next release
