### ISSUE TITLE
Card does not show after latest update

### ISSUE THREAD

**Issue by Repsionu** [MrBartusek/MeteoalarmCard#5]
**Describe the bug**
Custom card does not show up in LL (red box and not found)

**To Reproduce**
Open LL view with card

**Expected behavior**
Have a card displayed
**Screenshots**
`meteoalarm-card.js:1:33 TypeError: Error resolving module specifier “lit-element”. Relative module specifiers must start with “./”, “../” or “/”.`
![HA_meteoalarm_state](https://user-images.githubusercontent.com/46962963/118450616-0f068a00-b6fd-11eb-942a-813b9cf674c0.png)

**System (please complete the following information):**
 - Card version: [latest]
 - Home assistant version: [latest]
 - Installation type: [HACS]

**Additional context**
Worked OK before todays first alert?

**Comment by MrBartusek** [comment]
Hey, please try reinstalling version `v1.3.0` once again, let me know if that resolves your issue

![image](https://user-images.githubusercontent.com/23432278/118486334-c5786800-b719-11eb-9b6a-d2768f4e62f1.png)

**Comment by Repsionu** [comment]
Reinstalled already, checked my folders and LL resources- all OK :-) Strange is that after reloading Meteoalarm integration the card showed up (nothing to report) and disappeared as soon as some alarm became active. Now waiting something to show up for binary_sensor.meteoalarmeu and see what happens. Will note You when behavior is more clear.
Thanks for a swift response...
Best, JR

**Comment by MrBartusek** [comment]
The card won't work properly with meteoalarmeu right now (#4) and will throw `TypeError: Cannot read property '1' of undefinied`. I think it only happens when there is warning active thought.
