### ISSUE TITLE
Hide card when there is no warning

### ISSUE THREAD

**Issue by Chritzel** [MrBartusek/MeteoalarmCard#54]
Hi, first of all, thanks for this very nice card! :) 

**Is your feature request related to a problem? Please describe.**
No problem, just something that would be useful for me :)

**Describe the solution you'd like**
Currently, the card is always shown. When there is no warning, it is shown with the text "No warning".
I would personally prefer the card to be hidden when there is no warning, and only to be shown, when there is a warning.

In the best case, this would just be optionally configurable, for example by a config parameter "show_only_on_warnings" or "hide_when_no_warning" or similar.

**Comment by MrBartusek** [comment]
Hey, I have this feature done on the https://github.com/MrBartusek/MeteoalarmCard/tree/hide-when-no-warning branch but it seems like home assistant applies a small margin to all cards and I'm not sure if that can be removed in any way:

![image](https://user-images.githubusercontent.com/23432278/139589361-3e520dbb-dfe9-4c6f-93ad-f83b1d2235e3.png)


![image](https://user-images.githubusercontent.com/23432278/139589260-befde9e2-8410-41a1-a8ec-6451c49d3bb5.png)

I'll keep this issue open for now till me or someone else comes up with a solution for that.

**Comment by Repsionu** [comment]
HA conditional card or [https://github.com/thomasloven/lovelace-state-switch](url)? Can not test now as Meteoalarm integration shows unavailable for a month already :-(
Best, JR

**Comment by MrBartusek** [comment]
This is now a part of https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v1.12.0. Thanks for the suggestion!
