### ISSUE TITLE
Change in translation (Dutch)

### ISSUE THREAD

**Issue by MDLefevere** [MrBartusek/MeteoalarmCard#65]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem but to a translation (Dutch)

**Describe the solution you'd like**
The dutch translation states "Waarschuwing geel mist" which if you read it indicates that we should be warned for yellow mist.
Same with the warning for red. In The Netherlands we use "Code Yellow of Code Red"

**Additional context**
Change the text to:

Geen Waarschuwingen
Code Geel:
Code Rood:

**Comment by MrBartusek** [comment]
Hey @BartEngelen can you take a look at that?

**Comment by BartEngelen** [comment]
Hello,
I changed it like requested.
Kind regards,
Bart Engelen

**Comment by MDLefevere** [comment]
Any update on this?.

I still have the weird translations even after last update.
If any help is needed i'm pleased to help.

**Comment by MDLefevere** [comment]
@MrBartusek 

Is there a way to edit it myself?. Or do you have an estimation of when i will be changed?

**Comment by MrBartusek** [comment]
@MDLefevere Sorry for no reply, it just got lost somewhere in my notifications. No, there is no any update on this issue. You can work on this but you need at least minimal knowledge of Git and workflow of creating PRs. If you really want to push it forward you can just write down all of the translations that you wanna get changed here and I will just make the PR.

**Comment by MrBartusek** [comment]
There hasn't been any activity in this issue recently so I will close it. Thanks for your contribution!
