### ISSUE TITLE
'Yellow' alert isn't parsed while using meteoFrance 

### ISSUE THREAD

**Issue by PetitSphincter** [MrBartusek/MeteoalarmCard#74]
**Describe the bug**
'Yellow' avalanche alert isn't parsed while using meteoFrance 

**To Reproduce**
Steps to reproduce the behavior (not sure about this):
1. Adding meteoFrance integration
2. Adding the weather alert card with sensor.31_weather_alert
3. Wait for an avalanche yellow warning
4. Error  : 

`Error: This entity (sensor.31_weather_alert) cannot be parsed by selected integration (meteofrance)!
type: custom:meteoalarm-card
entity: sensor.31_weather_alert
hide_when_no_warning: true
integration: meteofrance (Tried automatic too)
override_headline: false`

**Expected behavior**
Today there's an avalanche yellow warning where i live, there's a yellow warning alert, i'm expecting a yellow alert on the card 

Logs : 

**System:**
 - Card version: 1.14.0
 -  Integration type: HAOS / Meteo-France
 - Installation type: HACS / Via interface

No specific logs in HA logs 

Attribute of my weather alert : 
Inondation Vert
Grand-froid Vert
Neige-verglas Vert
Orages Vert
Pluie-inondation Vert
Vent violent Vert
**Avalanches Jaune** (avalanche yellow)

**Comment by MrBartusek** [comment]
@Nsbx can you take a look?

**Comment by Nsbx** [comment]
Hey @MrBartusek :)
I came back from holiday right now.
I take a look next week (or Sunday if i'm not too tired)
