### ISSUE TITLE
Add Environnement Canada support

### ISSUE THREAD

**Issue by lappat** [MrBartusek/MeteoalarmCard#77]
Hi,

it is possible to add environement Canada integration?

regards

Patrick

**Comment by MrBartusek** [comment]
Hey, thanks for the suggestion! Environnement Canada integration was added to the [2.0](https://github.com/MrBartusek/MeteoalarmCard/tree/2.0?rgh-link-date=2022-06-12T23%3A02%3A27Z) branch. You will be able to use this integration starting from version v2.0.0 which will be released soon.

**Comment by MrBartusek** [comment]
This integration is now part of the new beta version [`v2.0.0-rc.1`](https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v2.0.0-rc.1). You can help to test changes in the new release. See more here: #88
