### ISSUE TITLE
entities not recognized

### ISSUE THREAD

**Issue by mfabiani53** [MrBartusek/MeteoalarmCard#93]
### Describe the bug

After installing the 2.00 release the card is not anymore showing as it asks an entities.

### Screenshots

![Schermata 2022-07-07 alle 21 06 58](https://user-images.githubusercontent.com/37701688/177852913-165f25c3-77ee-4d9d-981b-871d0971756d.png)
This is what i get after applying the breaking changes to the fronted card

### Card version

v2.0.0

### Integration type

Meteoalarm

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```
                  - type: custom:meteoalarm-card
                    entities: 'binary_sensor.allarme_meteo_abruzzo'
                    integration: 'meteoalarm'
```

### Integration Configuration

```
- platform: meteoalarm
  name: 'Allarme Meteo Abruzzo'
  language: 'it'
  country: "italy"
  province: "Abruzzo"
```

**Comment by MrBartusek** [comment]
Hey! I am not able to reproduce this issue. While running the same integration and card configuration my card is rendering correctly.

![image](https://user-images.githubusercontent.com/23432278/177860721-68840402-de25-4fdb-a387-6de53cd7caf5.png)

The only solution I can think of is you are using an old version of the card while using the new config. Please check which version of the card you are running by accessing your's browser developer console. It should look something like this.

![image](https://user-images.githubusercontent.com/23432278/177860623-b9ce8ac3-f9c5-47b7-904e-ec35f6e51b83.png)

If it's not `2.0.0` - please update the card if it is, try clearing your browser cache.

Please let me know if it fixes the issue!

**Comment by mfabiani53** [comment]
I deleted and reinstalled the card, cleared browser cache and the card is now working...
Thanks!

**Comment by MrBartusek** [comment]
Happy to help!
